In [1]:
# Working on the Uber Drivers dataset 
# Geography: USA, Sri Lanka and Pakistan
# Time period: January - December 2016
# Unit of analysis: Drives
# Total Drives: 1,155
# Total Miles: 12,204
# Dataset: The dataset contains 
# (Start Date, End Date, Start Location, End Location, Miles Driven and Purpose of drive (Business, Personal, Meals, Errands, Meetings, Customer Support etc.)

In [3]:
import pandas as pd
df_path  = "uber_drivers_2016.csv"
df = pd.read_csv(df_path)

In [4]:
df.head()

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit

In [5]:
df.columns

Index(['START_DATE*', 'END_DATE*', 'CATEGORY*', 'START*', 'STOP*', 'MILES*',
       'PURPOSE*'],
      dtype='object')

In [6]:
df.columns = df.columns.str.replace("*", "", regex=False)

print(df.columns)

Index(['START_DATE', 'END_DATE', 'CATEGORY', 'START', 'STOP', 'MILES',
       'PURPOSE'],
      dtype='object')

In [7]:
df.dtypes

START_DATE     object
END_DATE       object
CATEGORY       object
START          object
STOP           object
MILES         float64
PURPOSE        object
dtype: object

In [8]:
df.shape

(1156, 7)

In [9]:
df.describe()

              MILES
count   1156.000000
mean      21.115398
std      359.299007
min        0.500000
25%        2.900000
50%        6.000000
75%       10.400000
max    12204.700000

In [11]:
df.info()

# when we run it we can seee the daata  of null values and which might have the duplicates of data 
# so now we check wether duplicates are present are not if present we are gonig drop them.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   START_DATE  1156 non-null   object
 1   END_DATE    1155 non-null   object
 2   CATEGORY    1155 non-null   object
 3   START       1155 non-null   object
 4   STOP        1155 non-null   object
 5   MILES       1156 non-null   float64
 6   PURPOSE     653 non-null    object
dtypes: float64(1), object(6)
memory usage: 63.3+ KB

In [12]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1151    False
1152    False
1153    False
1154    False
1155    False
Length: 1156, dtype: bool

In [13]:
df.duplicated().sum()
# we can see how many duplicate rows are there

1

In [14]:
# so we need to get which row is duplicate

df[df.duplicated() == True]

          START_DATE         END_DATE  CATEGORY   START  STOP  MILES  PURPOSE
492  6/28/2016 23:34  6/28/2016 23:59  Business  Durham  Cary    9.9  Meeting

In [15]:
# we just got the duplicate row now we can delete with drop duplicate method 
# But i need to see the its original occurence als oso
df[df.duplicated(keep=False)]

          START_DATE         END_DATE  CATEGORY   START  STOP  MILES  PURPOSE
491  6/28/2016 23:34  6/28/2016 23:59  Business  Durham  Cary    9.9  Meeting
492  6/28/2016 23:34  6/28/2016 23:59  Business  Durham  Cary    9.9  Meeting

In [16]:
# Above we can see the original and duplicate rows s othere are nearby and easily we got
# if the original and duplicates are far apart we make tkae large to find so its good to sort the rows based on some row when working with large datasets.
# now lwts drop the duplicates

df = df.drop_duplicates() 

# we are changing the just thee df object but not delteting it from the file data if we wnant ot don the we nee to run the below command
#df.drop_duplicates(inpalce = True)

In [17]:
# we can see theere is a removal of duplicate row
# now lets check it by getting the duplicates sum

df.duplicated().sum()

# we got 0 so we are taknig data that don not have the duplicates.

0

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1155 entries, 0 to 1155
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   START_DATE  1155 non-null   object
 1   END_DATE    1154 non-null   object
 2   CATEGORY    1154 non-null   object
 3   START       1154 non-null   object
 4   STOP        1154 non-null   object
 5   MILES       1155 non-null   float64
 6   PURPOSE     652 non-null    object
dtypes: float64(1), object(6)
memory usage: 72.2+ KB

In [19]:
df.isnull()

      START_DATE  END_DATE  CATEGORY  START   STOP  MILES  PURPOSE
0          False     False     False  False  False  False    False
1          False     False     False  False  False  False     True
2          False     False     False  False  False  False    False
3          False     False     False  False  False  False    False
4          False     False     False  False  False  False    False
...          ...       ...       ...    ...    ...    ...      ...
1151       False     False     False  False  False  False    False
1152       False     False     False  False  False  False    False
1153       False     False     False  False  False  False    False
1154       False     False     False  False  False  False    False
1155       False      True      True   True   True  False     True

[1155 rows x 7 columns]

In [20]:
df.isnull().sum()

START_DATE      0
END_DATE        1
CATEGORY        1
START           1
STOP            1
MILES           0
PURPOSE       503
dtype: int64

In [21]:
# we can filter te data based on oyr required condition so its changes based on out requirement.
df[(df['MILES'] > 5) ]

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit
6,1/6/2016 17:30,1/6/2016 17:35,Business,West Palm Beach,Palm Beach,7.1,Meeting
8,1/10/2016 8:05,1/10/2016 8:25,Business,Cary,Morrisville,8.3,Meeting
9,1/10/2016 12:17,1/10/2016 12:44,Business,Jamaica,New York,16.5,Customer Visit
...,...,...,...,...,...,...,...
1144,12/29/2016 23:14,12/29/2016 23:47,Business,Unknown Location,Kar?chi,12.9,Meeting
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [22]:
df.sort_values(by="MILES",ascending = True)# df.sort_values(by="MILES",ascending = True)

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE
420,6/8/2016 17:16,6/8/2016 17:18,Business,Soho,Tribeca,0.5,Errand/Supplies
120,2/17/2016 16:38,2/17/2016 16:43,Business,Katunayaka,Katunayaka,0.5,Errand/Supplies
44,1/26/2016 17:27,1/26/2016 17:29,Business,Cary,Cary,0.5,Errand/Supplies
1110,12/24/2016 22:04,12/24/2016 22:09,Business,Lahore,Lahore,0.6,Errand/Supplies
516,7/5/2016 16:48,7/5/2016 16:52,Business,Whitebridge,Whitebridge,0.6,Errand/Supplies
...,...,...,...,...,...,...,...
776,9/27/2016 21:01,9/28/2016 2:37,Business,Unknown Location,Unknown Location,195.6,NaN
881,10/30/2016 15:22,10/30/2016 18:23,Business,Asheville,Mebane,195.9,NaN
270,3/25/2016 22:54,3/26/2016 1:39,Business,Jacksonville,Kissimmee,201.0,Meeting
269,3/25/2016 16:52,3/25/2016 22:22,Business,Latta,Jacksonville,310.3,Customer Visit
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [23]:
df.sort_values(by=["START_DATE","MILES"],ascending = [True,False])
# here we are sorting the data like startt date abnd miles based , where start date in ascending order and miles in desending order

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
9,1/10/2016 12:17,1/10/2016 12:44,Business,Jamaica,New York,16.5,Customer Visit
10,1/10/2016 15:08,1/10/2016 15:51,Business,New York,Queens,10.8,Meeting
11,1/10/2016 18:18,1/10/2016 18:53,Business,Elmhurst,New York,7.5,Meeting
12,1/10/2016 19:12,1/10/2016 19:32,Business,Midtown,East Harlem,6.2,Meeting
...,...,...,...,...,...,...,...
779,9/30/2016 17:39,9/30/2016 20:20,Business,Islamabad,Islamabad,37.7,NaN
780,9/30/2016 20:59,9/30/2016 22:34,Business,Islamabad,Unknown Location,16.7,NaN
750,9/5/2016 10:25,9/5/2016 10:44,Business,Unknown Location,R?walpindi,17.2,NaN
751,9/6/2016 17:49,9/6/2016 17:49,Business,Unknown Location,Unknown Location,69.1,NaN
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [24]:
df.isnull().sum()

START_DATE      0
END_DATE        1
CATEGORY        1
START           1
STOP            1
MILES           0
PURPOSE       503
dtype: int64

In [25]:
# so we can see that we have more null values in porpose of rides so lets make to unknown
df["PURPOSE"] = df["PURPOSE"].fillna("Unknown")
df.isnull().sum()

START_DATE    0
END_DATE      1
CATEGORY      1
START         1
STOP          1
MILES         0
PURPOSE       0
dtype: int64

In [26]:
# s owe are okay with pupose null vlaues
# now lwts see about the columns which are having the only one missing value
# actually removing that null valued row is not good decision but for lets remove tat row for better visuvalization.
df = df.dropna(subset = ["END_DATE", "CATEGORY", "START", "STOP"])

In [27]:
# so lets check the null values present or not
df.isnull().sum()


# see what are we doing like changing the null values to unknown and removing rows was effect the actual data
# we are changing the obejct of df we are having.

START_DATE    0
END_DATE      0
CATEGORY      0
START         0
STOP          0
MILES         0
PURPOSE       0
dtype: int64

In [28]:
df = df[df["START_DATE"] != "Totals"].copy()
df

# actually total is also a row here so when we want to perform some funtions we dont want that to do for this

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,Unknown
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit
...,...,...,...,...,...,...,...
1150,12/31/2016 1:07,12/31/2016 1:14,Business,Kar?chi,Kar?chi,0.7,Meeting
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site

In [29]:
# so done with null values go lets go witth data segrigation like 

# lets first convert start date and endte to to_datetime format

df["START_DATE"] = pd.to_datetime(df["START_DATE"])
df["END_DATE"] = pd.to_datetime(df["END_DATE"])
df

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE
0,2016-01-01 21:11:00,2016-01-01 21:17:00,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,2016-01-02 01:25:00,2016-01-02 01:37:00,Business,Fort Pierce,Fort Pierce,5.0,Unknown
2,2016-01-02 20:25:00,2016-01-02 20:38:00,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,2016-01-05 17:31:00,2016-01-05 17:45:00,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,2016-01-06 14:42:00,2016-01-06 15:49:00,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit
...,...,...,...,...,...,...,...
1150,2016-12-31 01:07:00,2016-12-31 01:14:00,Business,Kar?chi,Kar?chi,0.7,Meeting
1151,2016-12-31 13:24:00,2016-12-31 13:42:00,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,2016-12-31 15:03:00,2016-12-31 15:38:00,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,2016-12-31 21:32:00,2016-12-31 21:50:00,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,2016-12-31 22:08:00,2016-12-31 23:51:00,Business,Gampaha,Ilukwatta,48.2,Temporary Site

In [30]:
# seprate the date and time start and end date which is hepful for the data visuvalization.
# for clear visuvalization lets have year,month,day,hour,day_name as seperate columns with out effecting the original START_DATE and END_DATE

df["START_YEAR"] = df["START_DATE"].dt.year
df["START_MONTH"] = df["START_DATE"].dt.month
df["START_DAY"] = df["START_DATE"].dt.day
df["START_HOUR"] = df["START_DATE"].dt.hour
df["DAY_NAME"] = df["START_DATE"].dt.day_name()

df

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE,START_YEAR,START_MONTH,START_DAY,START_HOUR,DAY_NAME
0,2016-01-01 21:11:00,2016-01-01 21:17:00,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain,2016,1,1,21,Friday
1,2016-01-02 01:25:00,2016-01-02 01:37:00,Business,Fort Pierce,Fort Pierce,5.0,Unknown,2016,1,2,1,Saturday
2,2016-01-02 20:25:00,2016-01-02 20:38:00,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies,2016,1,2,20,Saturday
3,2016-01-05 17:31:00,2016-01-05 17:45:00,Business,Fort Pierce,Fort Pierce,4.7,Meeting,2016,1,5,17,Tuesday
4,2016-01-06 14:42:00,2016-01-06 15:49:00,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit,2016,1,6,14,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...
1150,2016-12-31 01:07:00,2016-12-31 01:14:00,Business,Kar?chi,Kar?chi,0.7,Meeting,2016,12,31,1,Saturday
1151,2016-12-31 13:24:00,2016-12-31 13:42:00,Business,Kar?chi,Unknown Location,3.9,Temporary Site,2016,12,31,13,Saturday
1152,2016-12-31 15:03:00,2016-12-31 15:38:00,Business,Unknown Location,Unknown Location,16.2,Meeting,2016,12,31,15,Saturday
1153,2016-12-31 21:32:00,2016-12-31 21:50:00,Business,Katunayake,Gampaha,6.4,Temporary Site,2016,12,31,21,Saturday
1154,2016-12-31 22:08:00,2016-12-31 23:51:00,Business,Gampaha,Ilukwatta,48.2,Temporary Site,2016,12,31,22,Saturday

In [31]:
# we have specoal character in start and stop columns
df[df.START.str.contains('\?') == True]

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE,START_YEAR,START_MONTH,START_DAY,START_HOUR,DAY_NAME
140,2016-02-20 14:50:00,2016-02-20 15:54:00,Business,R?walpindi,R?walpindi,23.1,Meeting,2016,2,20,14,Saturday
141,2016-02-20 16:59:00,2016-02-20 17:54:00,Personal,R?walpindi,Unknown Location,16.5,Unknown,2016,2,20,16,Saturday
656,2016-08-15 09:05:00,2016-08-15 09:52:00,Business,R?walpindi,Unknown Location,15.6,Unknown,2016,8,15,9,Monday
670,2016-08-17 15:32:00,2016-08-17 15:47:00,Business,R?walpindi,Islamabad,6.4,Unknown,2016,8,17,15,Wednesday
679,2016-08-19 10:57:00,2016-08-19 11:06:00,Business,R?walpindi,Unknown Location,2.0,Unknown,2016,8,19,10,Friday
696,2016-08-22 20:53:00,2016-08-22 21:31:00,Business,R?walpindi,R?walpindi,4.1,Unknown,2016,8,22,20,Monday
697,2016-08-22 22:31:00,2016-08-22 23:00:00,Business,R?walpindi,Unknown Location,18.7,Unknown,2016,8,22,22,Monday
763,2016-09-19 06:18:00,2016-09-19 06:49:00,Business,R?walpindi,Unknown Location,18.2,Unknown,2016,9,19,6,Monday
788,2016-10-06 17:23:00,2016-10-06 17:40:00,Business,R?walpindi,Unknown Location,112.6,Unknown,2016,10,6,17,Thursday
804,2016-10-12 19:18:00,2016-10-12 19:21:00,Business,R?walpindi,Unknown Location,18.4,Unknown,2016,10,12,19,Wednesday
811,2016-10-14 10:16:00,2016-10-14 10:52:00,Business,R?walpindi,Unknown Location,12.4,Unknown,2016,10,14,10,Friday
1119,2016-12-27 07:02:00,2016-12-27 07:14:00,Business,Kar?chi,Kar?chi,4.9,Temporary Site,2016,12,27,7,Tuesday
1120,2016-12-27 08:37:00,2016-12-27 08:59:00,Business,Kar?chi,Kar?chi,5.0,Meal/Entertain,2016,12,27,8,Tuesday
1121,2016-12-27 12:53:00,2016-12-27 12:57:00,Business,Kar?chi,Kar?chi,0.6,Meal/Entertain,2016,12,27,12,Tuesday
1122,2016-12-27 14:49:00,2016-12-27 15:03:00,Business,Kar?chi,Unknown Location,3.1,Customer Visit,2016,12,27,14,Tuesday
1124,2016-12-27 19:19:00,2016-12-27 19:50:00,Business,Kar?chi,Kar?chi,5.5,Customer Visit,2016,12,27,19,Tuesday
1125,2016-12-28 08:34:00,2016-12-28 09:06:00,Business,Kar?chi,Unknown Location,10.3,Meal/Entertain,2016,12,28,8,Wednesday
1127,2016-12-28 13:53:00,2016-12-28 14:01:00,Business,Kar?chi,Kar?chi,2.0,Errand/Supplies,2016,12,28,13,Wednesday
1128,2016-12-28 15:04:00,2016-12-28 15:39:00,Business,Kar?chi,Unknown Location,8.5,Meal/Entertain,2016,12,28,15,Wednesday
1130,2016-12-28 18:33:00,2016-12-28 18:56:00,Business,Kar?chi,Kar?chi,3.8,Errand/Supplies,2016,12,28,18,Wednesday
1131,2016-12-28 22:44:00,2016-12-28 23:18:00,Business,Kar?chi,Kar?chi,5.1,Errand/Supplies,2016,12,28,22,Wednesday
1132,2016-12-29 00:49:00,2016-12-29 01:06:00,Business,Kar?chi,Kar?chi,3.8,Errand/Supplies,2016,12,29,0,Thursday
1133,2016-12-29 09:44:00,2016-12-29 10:07:00,Business,Kar?chi,Unknown Location,11.6,Meal/Entertain,2016,12,29,9,Thursday
1135,2016-12-29 12:25:00,2016-12-29 12:33:00,Business,Kar?chi,Kar?chi,1.4,Errand/Supplies,2016,12,29,12,Thursday
1136,2016-12-29 13:17:00,2016-12-29 13:24:00,Business,Kar?chi,Kar?chi,1.1,Errand/Supplies,2016,12,29,13,Thursday
1137,2016-12-29 13:56:00,2016-12-29 14:11:00,Business,Kar?chi,Kar?chi,4.1,Airport/Travel,2016,12,29,13,Thursday
1138,2016-12-29 14:42:00,2016-12-29 14:58:00,Business,Kar?chi,Kar?chi,6.1,Between Offices,2016,12,29,14,Thursday
1139,2016-12-29 15:05:00,2016-12-29 15:16:00,Business,Kar?chi,Kar?chi,1.3,Errand/Supplies,2016,12,29,15,Thursday
1140,2016-12-29 18:59:00,2016-12-29 19:14:00,Business,Kar?chi,Unknown Location,3.0,Meal/Entertain,2016,12,29,18,Thursday
1142,2016-12-29 20:15:00,2016-12-29 20:45:00,Business,Kar?chi,Kar?chi,7.2,Meeting,2016,12,29,20,Thursday
1143,2016-12-29 20:53:00,2016-12-29 21:42:00,Business,Kar?chi,Unknown Location,6.4,Unknown,2016,12,29,20,Thursday
1145,2016-12-30 10:15:00,2016-12-30 10:33:00,Business,Kar?chi,Kar?chi,2.8,Errand/Supplies,2016,12,30,10,Friday
1146,2016-12-30 11:31:00,2016-12-30 11:56:00,Business,Kar?chi,Kar?chi,2.9,Errand/Supplies,2016,12,30,11,Friday
1147,2016-12-30 15:41:00,2016-12-30 16:03:00,Business,Kar?chi,Kar?chi,4.6,Errand/Supplies,2016,12,30,15,Friday
1148,2016-12-30 16:45:00,2016-12-30 17:08:00,Business,Kar?chi,Kar?chi,4.6,Meeting,2016,12,30,16,Friday
1149,2016-12-30 23:06:00,2016-12-30 23:10:00,Business,Kar?chi,Kar?chi,0.8,Customer Visit,2016,12,30,23,Friday
1150,2016-12-31 01:07:00,2016-12-31 01:14:00,Business,Kar?chi,Kar?chi,0.7,Meeting,2016,12,31,1,Saturday
1151,2016-12-31 13:24:00,2016-12-31 13:42:00,Business,Kar?chi,Unknown Location,3.9,Temporary Site,2016,12,31,13,Saturday

In [36]:
# IF w observe the data we can see that there a special character in the staat and stop destinstion of the places 
# so we habvve to change it 


df["START"] = df["START"].replace({"\?":"a"},regex = True)
df["STOP"] = df["STOP"].replace({"\?":"a"},regex = True)
df

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE,START_YEAR,START_MONTH,START_DAY,START_HOUR,DAY_NAME
0,2016-01-01 21:11:00,2016-01-01 21:17:00,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain,2016,1,1,21,Friday
1,2016-01-02 01:25:00,2016-01-02 01:37:00,Business,Fort Pierce,Fort Pierce,5.0,Unknown,2016,1,2,1,Saturday
2,2016-01-02 20:25:00,2016-01-02 20:38:00,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies,2016,1,2,20,Saturday
3,2016-01-05 17:31:00,2016-01-05 17:45:00,Business,Fort Pierce,Fort Pierce,4.7,Meeting,2016,1,5,17,Tuesday
4,2016-01-06 14:42:00,2016-01-06 15:49:00,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit,2016,1,6,14,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...
1150,2016-12-31 01:07:00,2016-12-31 01:14:00,Business,Karachi,Karachi,0.7,Meeting,2016,12,31,1,Saturday
1151,2016-12-31 13:24:00,2016-12-31 13:42:00,Business,Karachi,Unknown Location,3.9,Temporary Site,2016,12,31,13,Saturday
1152,2016-12-31 15:03:00,2016-12-31 15:38:00,Business,Unknown Location,Unknown Location,16.2,Meeting,2016,12,31,15,Saturday
1153,2016-12-31 21:32:00,2016-12-31 21:50:00,Business,Katunayake,Gampaha,6.4,Temporary Site,2016,12,31,21,Saturday
1154,2016-12-31 22:08:00,2016-12-31 23:51:00,Business,Gampaha,Ilukwatta,48.2,Temporary Site,2016,12,31,22,Saturday

In [37]:
# lets convert this data frame to a CSV file which is data cleaned and segrigated dat aso we can work on this data later 
# for visuvalization

# df.to_csv('preProcessedUberDrivers2016.csv',index= False)  #remove it from comment if need to download this data frame.