In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df1 = pd.read_csv('challenging_gym_members_60900.csv')
df1.head(10)

,MemberID,FullName,Email,Phone,Gender,DateOfBirth,Age,City,Branch,MembershipPlan,...,Trainer,AttendancePerMonth,AvgWorkoutMinutes,SessionsCompleted,CustomerRating,HeightCm,WeightKg,BMI,LeadSource,LastVisitDate
0,M100000,Sneha Kumar,rahul.rao0@example.com,+91-8555928865,m,1971-02-17,55,Tiruchirappalli,Madurai South,Platinum,...,Priya S,7,44,21,4.8,157.5,87.3,35.19,Walk-in,2023-11-26
1,M100001,Suresh Patel,suresh.iyer1@example.com,+91-8572454672,M,1983-11-18,42,Coimbatore,Pune West,Basic,...,Divya T,7,50,9,1.4,184.7,44.3,12.99,Google Ads,2027-03-15
2,M100002,Divya Reddy,suresh.das2@example.com,+91-8641006265,Female,2002-02-03,24,Visakhapatnam,Bangalore East,Student,...,Arun K,9,67,26,4.4,159.2,34.0,13.42,Referral,2025-07-23
3,M100003,Sneha Rao,karthik.kumar3@example.com,+91-8731328501,Female,1998-02-23,28,Delhi,Mumbai Central,Platinum,...,Rahul M,10,73,17,1.2,165.4,65.5,23.94,Referral,2025-04-27
4,M100004,Swathi Sharma,karthik.das4@example.com,+91-9566756567,female,1988-05-16,38,Mysuru,Vellore North,Family,...,Anjali V,11,54,15,1.4,165.5,77.3,28.22,Corporate,2028-06-04
5,M100005,Aditya Nair,pooja.kumar5@example.com,NaN,Male,1997-04-12,29,Madurai,Mumbai Central,Basic,...,Karthik N,11,22,12,1.3,159.9,95.4,37.31,Google Ads,2022-06-02
6,M100006,Priya Kumar,pooja.iyer6@example.com,+91-6825018365,Male,1968-06-16,58,Mysuru,Madurai South,Student,...,Arun K,13,40,-10,3.1,186.1,82.3,23.76,Partner,2025-11-13
7,M100007,Rahul Patel,neha.sharma7@example.com,+91-9985354754,Female,1977-01-18,49,Delhi,Coimbatore Main,Premium,...,Karthik N,7,53,14,2.1,158.7,87.8,34.86,Facebook,2024-07-18
8,M100008,Divya Das,vikram.das8@example.com,+91-8228181865,Female,1973-02-21,53,Coimbatore,Kochi Marine,Premium,...,Divya T,7,52,11,3.0,185.4,81.6,23.74,Facebook,2025-04-06
9,M100009,Ishita Kumar,sneha.reddy9@example.com,+91-9115346340,Female,1962-07-06,64,Salem,Bangalore East,Platinum,...,Divya T,7,69,19,4.8,165.0,71.9,26.41,Partner,2022-01-21

In [3]:
df2 = pd.read_csv('challenging_gym_transactions_18000.csv')
df2.head(10)

,TransactionID,MemberID,TransactionDate,Amount,PaymentMethod,TransactionType,PaymentStatus
0,T500000,M121921,2025-01-20,484.81,EMI,Membership,Success
1,T500001,M125493,2022-05-19,1971.58,Net Banking,Merchandise,Pending
2,T500002,M158910,2022-05-15,1610.19,UPI,Personal Training,Success
3,T500003,M102787,2021-04-14,3155.65,Wallet,Class,Failed
4,T500004,M155307,2021-03-28,1277.26,Cash,Renewal,Success
5,T500005,M125201,2021-10-26,2688.45,upi,Merchandise,Success
6,T500006,M107115,2023-01-10,896.2,UPI,Refund,Failed
7,T500007,M132149,2022-09-29,3707.97,EMI,Merchandise,Success
8,T500008,M119507,2021-03-09,1291.64,UPI,Personal Training,Pending
9,T500009,M148712,2023-03-16,1119.65,Credit Card,Class,SUCCESS

In [4]:
df3 = pd.read_csv('challenging_gym_dataset_guide.csv')
df3

               Challenge                                   What is included
0         Missing values                        Different missingness rates
1             Duplicates                            Exact + near duplicates
2   Categorical cleaning          Case, spelling, whitespace, abbreviations
3             Validation                             Email and phone errors
4               Outliers  Age, BMI, height, weight, fees, ratings, atten...
5                  Dates  Mixed formats, impossible/future dates, chrono...
6        Numeric parsing                    ₹, commas, numeric strings, N/A
7          Logical rules       Status vs visits/attendance, discount issues
8                  Joins                   300 orphan transaction MemberIDs
9                    EDA  Revenue, churn, attendance, plans, branches, t...
10         Preprocessing  Imputation, encoding, scaling, outlier handlin...
11                    ML  Churn prediction, segmentation, revenue predic...

In [5]:
df1.loc[9]

MemberID                               M100009
FullName                          Ishita Kumar
Email                 sneha.reddy9@example.com
Phone                           +91-9115346340
Gender                                  Female
DateOfBirth                         1962-07-06
Age                                         64
City                                     Salem
Branch                          Bangalore East
MembershipPlan                        Platinum
JoinDate                   2021-05-11 00:00:00
MembershipStatus                        Active
MonthlyFee                                3999
DiscountPercent                             10
Revenue                                 3599.1
PaymentMethod                           Wallet
WorkoutType                             Cardio
Trainer                                Divya T
AttendancePerMonth                           7
AvgWorkoutMinutes                           69
SessionsCompleted                           19
CustomerRating                             4.8
HeightCm                                 165.0
WeightKg                                  71.9
BMI                                      26.41
LeadSource                             Partner
LastVisitDate                       2022-01-21
Name: 9, dtype: object

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60900 entries, 0 to 60899
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   MemberID            60900 non-null  object
 1   FullName            60900 non-null  object
 2   Email               59264 non-null  object
 3   Phone               58668 non-null  object
 4   Gender              59866 non-null  object
 5   DateOfBirth         60900 non-null  object
 6   Age                 60900 non-null  int64
 7   City                60217 non-null  object
 8   Branch              60900 non-null  object
 9   MembershipPlan      60900 non-null  object
 10  JoinDate            60850 non-null  object
 11  MembershipStatus    60900 non-null  object
 12  MonthlyFee          60900 non-null  object
 13  DiscountPercent     60900 non-null  int64
 14  Revenue             60900 non-null  object
 15  PaymentMethod       59766 non-null  object
 16  WorkoutType         60900 non-null  object
 17  Trainer             59077 non-null  object
 18  AttendancePerMonth  60900 non-null  int64
 19  AvgWorkoutMinutes   60900 non-null  int64
 20  SessionsCompleted   60900 non-null  int64
 21  CustomerRating      58161 non-null  float64
 22  HeightCm            59688 non-null  object
 23  WeightKg            59380 non-null  object
 24  BMI                 60900 non-null  float64
 25  LeadSource          60900 non-null  object
 26  LastVisitDate       58506 non-null  object
dtypes: float64(2), int64(5), object(20)
memory usage: 12.5+ MB

Here we have various columns that need tremendous changes
1. phone must be integer and remove first three numbers
2. dob to datetime
3. join date to datetime
4. monthly fees to number
5. check revenue and convert to int
6. Height weight to float
7. last visit date

In [7]:
df1['City'].unique()

array(['Tiruchirappalli', 'Coimbatore', 'Visakhapatnam', 'Delhi',
       'Mysuru', 'Madurai', 'Salem', 'Vellore', 'Vijayawada', 'Bengaluru',
       'BENGALURU ', 'Pune', 'Kochi', 'Chennai', 'Hyderabad',
       '  Tiruchirappalli  ', 'Mumbai', '  Madurai  ', 'Bangalore', nan,
       ' Bengaluru', 'bangalore', '  Pune  ', '  Mysuru  ',
       '   Bengaluru  ', '  Vijayawada  ', '  Kochi  ', '  Chennai  ',
       '  Delhi  ', '  Mumbai  ', '  Visakhapatnam  ', '  Hyderabad  ',
       '  Vellore  ', '  Bengaluru  ', '  Salem  ', '  Coimbatore  ',
       '  Bangalore  ', '  bangalore  ', '  BENGALURU   '], dtype=object)

In [8]:
def mod_pho(val):
    if val == np.nan:
        return
    else:
        return str(val)
    return val
df1['Phone'] = df1['Phone'].apply(mod_pho)
df1['Phone']

0        +91-8555928865
1        +91-8572454672
2        +91-8641006265
3        +91-8731328501
4        +91-9566756567
              ...
60895    +91-7022620146
60896    +91-8695549390
60897    +91-8153970868
60898    +91-9682177751
60899    +91-7329162706
Name: Phone, Length: 60900, dtype: object

In [9]:
df1['Phone'] = df1['Phone'].apply(lambda x: x[4:])

In [10]:
df1['Phone'].unique()

array(['8555928865', '8572454672', '8641006265', ..., '8669856119',
       '9228554207', '7338886793'], dtype=object)

In [11]:
def mod_phon(val):
    try:
        return int(val)
    except:
        return val

df1['Phone'] = df1['Phone'].apply(mod_phon)

In [12]:
df1['Phone'].apply(type).value_counts()

Phone
<class 'int'>    58555
<class 'str'>     2345
Name: count, dtype: int64

In [13]:
def mod_phon(val):
    if isinstance(val, str):
        return 'Not Given'
    else:
        return val

df1['Phone'] = df1['Phone'].apply(mod_phon)

In [14]:
df1['Phone'].isnull().sum()

0

In [15]:
df1.head(100)

,MemberID,FullName,Email,Phone,Gender,DateOfBirth,Age,City,Branch,MembershipPlan,...,Trainer,AttendancePerMonth,AvgWorkoutMinutes,SessionsCompleted,CustomerRating,HeightCm,WeightKg,BMI,LeadSource,LastVisitDate
0,M100000,Sneha Kumar,rahul.rao0@example.com,8555928865,m,1971-02-17,55,Tiruchirappalli,Madurai South,Platinum,...,Priya S,7,44,21,4.8,157.5,87.3,35.19,Walk-in,2023-11-26
1,M100001,Suresh Patel,suresh.iyer1@example.com,8572454672,M,1983-11-18,42,Coimbatore,Pune West,Basic,...,Divya T,7,50,9,1.4,184.7,44.3,12.99,Google Ads,2027-03-15
2,M100002,Divya Reddy,suresh.das2@example.com,8641006265,Female,2002-02-03,24,Visakhapatnam,Bangalore East,Student,...,Arun K,9,67,26,4.4,159.2,34.0,13.42,Referral,2025-07-23
3,M100003,Sneha Rao,karthik.kumar3@example.com,8731328501,Female,1998-02-23,28,Delhi,Mumbai Central,Platinum,...,Rahul M,10,73,17,1.2,165.4,65.5,23.94,Referral,2025-04-27
4,M100004,Swathi Sharma,karthik.das4@example.com,9566756567,female,1988-05-16,38,Mysuru,Vellore North,Family,...,Anjali V,11,54,15,1.4,165.5,77.3,28.22,Corporate,2028-06-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,M100095,Neha Mishra,karthik.das95@example.com,8744748412,Female,2006-04-25,20,Kochi,Kochi Marine,Premium,...,Sneha R,4,47,18,1.2,173.1,44.8,14.95,Walk-in,2027-03-10
96,M100096,Meena Patel,rahul.pillai96@example.com,8983786026,male,1981-06-10,45,Coimbatore,Madurai South,Gold,...,Sneha R,7,69,17,3.6,155.2,62.8,26.07,Partner,2024-10-10
97,M100097,Priya Patel,vikram.verma97@example.com,7969040792,female,1961-09-25,64,Bangalore,Coimbatore Main,Platinum,...,Rahul M,7,66,21,4.1,168.3,NaN,27.29,Referral,2024-02-20
98,M100098,Aditya Sharma,suresh.nair98@example.com,7294197054,female,2007-06-23,19,Mumbai,Mumbai Central,Gold,...,Priya S,10,65,17,4.6,161.1,93.3,35.95,Partner,2024-07-18
99,M100099,Rahul Joshi,neha.mishra99@example.com,7748728962,m,1991-11-27,34,Mysuru,Mumbai Central,Premium,...,Sneha R,17,38,22,3.8,174.5,77.3,25.39,Partner,2021-04-16

In [16]:
df1['Gender'].unique()

array(['m', 'M', 'Female', 'female', 'Male', nan, ' M ', 'Other', 'male',
       'Non-binary', 'F', 'f', 'non-binary', 'FEMALE', 'other', 'MALE',
       ' Female '], dtype=object)

In [17]:
def gend_mod(val):
    if val in ['m','Male','M', 'male', 'MALE']:
        return 'Male'
    elif val in ['Female','female','F','f','FEMALE']:
        return 'Female'
    elif val is np.nan:
        return 'not Given'
    else:
        return val.capitalize()


df1['Gender'] = df1['Gender'].str.strip()

In [18]:
df1['Gender'] = df1['Gender'].apply(gend_mod)

In [19]:
len(df1['DateOfBirth'].unique())

16937

In [20]:
df1['DateOfBirth'] = pd.to_datetime(df1['DateOfBirth'])

In [21]:
type(df1['DateOfBirth'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [22]:
df1['DateOfBirth'].isnull().sum()

0

In [23]:
df1['City'].unique()

array(['Tiruchirappalli', 'Coimbatore', 'Visakhapatnam', 'Delhi',
       'Mysuru', 'Madurai', 'Salem', 'Vellore', 'Vijayawada', 'Bengaluru',
       'BENGALURU ', 'Pune', 'Kochi', 'Chennai', 'Hyderabad',
       '  Tiruchirappalli  ', 'Mumbai', '  Madurai  ', 'Bangalore', nan,
       ' Bengaluru', 'bangalore', '  Pune  ', '  Mysuru  ',
       '   Bengaluru  ', '  Vijayawada  ', '  Kochi  ', '  Chennai  ',
       '  Delhi  ', '  Mumbai  ', '  Visakhapatnam  ', '  Hyderabad  ',
       '  Vellore  ', '  Bengaluru  ', '  Salem  ', '  Coimbatore  ',
       '  Bangalore  ', '  bangalore  ', '  BENGALURU   '], dtype=object)

In [24]:
df1['City'] = df1['City'].str.strip()

In [25]:
df1['City'] = df1['City'].apply(lambda x : 'Bengaluru' if x in ['BENGALURU','Bangalore','bangalore'] else x)

In [26]:
df1['City'].fillna('Not given', inplace=True)

In [27]:
df1['City'].isnull().sum()

0

In [28]:
df1['Branch'].value_counts()

Branch
Madurai South          6017
Vellore North          6000
Delhi NCR              5982
Hyderabad Hub          5969
Kochi Marine           5930
Coimbatore Main        5894
Pune West              5890
Bangalore East         5862
Mumbai Central         5802
Chennai Central        5754
  Chennai Central       205
  Pune West             198
  Mumbai Central        185
  Hyderabad Hub         181
  Madurai South         178
  Bangalore East        178
  Vellore North         172
  Coimbatore Main       169
  Kochi Marine          167
  Delhi NCR             167
Name: count, dtype: int64

In [29]:
df1['Branch'] = df1['Branch'].str.strip()

In [30]:
df1['Branch'].isnull().sum()

0

In [31]:
df1['MembershipPlan'].unique()

array(['Platinum', 'Basic', 'Student', 'Family', 'Premium', 'Gold',
       'PREMIUM', 'basic', 'premium', '  Premium  ', '  Family  ',
       '  premium  ', ' BASIC ', 'Premium ', '  Gold  ', '  Platinum  ',
       '  Basic  ', '  basic  ', '  Student  ', '  PREMIUM  ',
       '  Premium   ', '   BASIC   '], dtype=object)

In [32]:
df1['MembershipPlan'] = df1['MembershipPlan'].str.strip().str.lower().str.capitalize()

In [33]:
df1['MembershipPlan'].isnull().sum()

0

In [34]:
type(df1['JoinDate'][0])

str

In [35]:
invalid_rows = df1[pd.to_datetime(df1['JoinDate'], format='%d%m%Y', errors='coerce').isna()]
invalid_rows.loc[10]

MemberID                              M100010
FullName                         Swathi Patel
Email                 rahul.das10@example.com
Phone                              6636805043
Gender                                 Female
DateOfBirth               1991-05-09 00:00:00
Age                                        35
City                                  Vellore
Branch                        Chennai Central
MembershipPlan                           Gold
JoinDate                  2025-08-13 00:00:00
MembershipStatus                       Active
MonthlyFee                                799
DiscountPercent                             5
Revenue                                759.05
PaymentMethod                      Debit Card
WorkoutType               Functional Training
Trainer                              Suresh G
AttendancePerMonth                         10
AvgWorkoutMinutes                          63
SessionsCompleted                          18
CustomerRating                            2.4
HeightCm                                165.0
WeightKg                                 75.6
BMI                                     27.77
LeadSource                         Google Ads
LastVisitDate                      2027-03-09
Name: 10, dtype: object

In [36]:
df1['JoinDate'] = pd.to_datetime(df1['JoinDate'],format='mixed',errors='coerce')

In [37]:
df1['JoinDate']

0       2023-05-11
1       2024-07-18
2       2024-02-05
3       2024-01-01
4       2025-06-27
           ...
60895   2023-01-12
60896   2023-05-08
60897   2024-08-22
60898   2023-01-25
60899   2021-12-12
Name: JoinDate, Length: 60900, dtype: datetime64[ns]

In [38]:
type(df1['JoinDate'][55])

pandas._libs.tslibs.nattype.NaTType

In [39]:
df1['JoinDate'].isnull().sum()

249

In [40]:
df1['MembershipStatus'].isnull().sum()

0

In [41]:
df1['MembershipStatus'].unique()

array(['Active', 'Inactive', 'Frozen', 'Pending', 'Cancelled'],
      dtype=object)

In [42]:
df1['DiscountPercent']

0        10
1         0
2         5
3         0
4        15
         ..
60895    25
60896     0
60897     5
60898    10
60899     0
Name: DiscountPercent, Length: 60900, dtype: int64

In [43]:
df1['DiscountPercent'].isnull().sum()

0

In [44]:
df1['DiscountPercent'] = df1["DiscountPercent"].apply(lambda x : abs(x) if x < 0 else x)

In [45]:
df1['Revenue']

0          719.1
1          999.0
2         759.05
3         2999.0
4        2124.15
          ...
60895     749.25
60896     1299.0
60897    3799.05
60898     3599.1
60899      999.0
Name: Revenue, Length: 60900, dtype: object

In [46]:
df1['Revenue'].isnull().sum()

0

In [47]:
df1['Revenue']  = pd.to_numeric(df1['Revenue'].str.replace('₹',"", regex=False).str.replace(",","", regex=False))

In [48]:
df1['Revenue'].isnull().sum()

0

In [49]:
df1['Revenue'].sum()

112108077.95

In [50]:
df1['MonthlyFee']

0         799
1         999
2         799
3        2999
4        2499
         ...
60895     999
60896    1299
60897    3999
60898    3999
60899     999
Name: MonthlyFee, Length: 60900, dtype: object

In [51]:
df1['MonthlyFee'] = pd.to_numeric(df1['MonthlyFee'].str.replace('₹','', regex=False).str.replace(',','', regex=False))

In [52]:
df1['MonthlyFee']

0         799.0
1         999.0
2         799.0
3        2999.0
4        2499.0
          ...
60895     999.0
60896    1299.0
60897    3999.0
60898    3999.0
60899     999.0
Name: MonthlyFee, Length: 60900, dtype: float64

In [53]:
df1['MonthlyFee'].isnull().sum()

0

In [54]:
df1['MonthlyFee'].sum()

127813936.0

In [55]:
df1['PaymentMethod']

0               Cash
1         Debit Card
2                EMI
3               Cash
4                UPI
            ...
60895    Credit Card
60896    Credit Card
60897         Wallet
60898            EMI
60899     Debit Card
Name: PaymentMethod, Length: 60900, dtype: object

In [56]:
df1['PaymentMethod'] = df1['PaymentMethod'].str.strip().str.lower().str.capitalize()

In [57]:
df1['PaymentMethod'].unique()

array(['Cash', 'Debit card', 'Emi', 'Upi', 'Credit card', 'Wallet',
       'Net banking', nan, 'Creditcard', 'Credit_card'], dtype=object)

In [58]:
df1['PaymentMethod'] = df1['PaymentMethod'].replace('Emi', "EMI")

In [59]:
df1['PaymentMethod'] = df1['PaymentMethod'].replace('Upi', "UPI")

In [60]:
df1['PaymentMethod'] = df1['PaymentMethod'].replace({'Credit_card': 'Credit card','Creditcard': 'Credit card', 'Credit card': 'Credit card'})

In [61]:
df1["PaymentMethod"].isnull().sum()

1134

In [62]:
df1['WorkoutType']

0        Swimming
1        Strength
2        CrossFit
3        Swimming
4            Yoga
           ...
60895     Pilates
60896        HIIT
60897       Zumba
60898    Swimming
60899    Strength
Name: WorkoutType, Length: 60900, dtype: object

In [63]:
df1['WorkoutType'].unique()

array(['Swimming', 'Strength', 'CrossFit', 'Yoga', 'Functional Training',
       'Cardio', '  Swimming  ', 'Pilates', 'Zumba', 'HIIT', '  Zumba  ',
       '  HIIT  ', '  Cardio  ', '  CrossFit  ', '  Yoga  ',
       '  Functional Training  ', '  Pilates  ', '  Strength  '],
      dtype=object)

In [64]:
df1['WorkoutType']=df1['WorkoutType'].str.strip()

In [65]:
df1['WorkoutType'].isnull().sum()

0

In [66]:
df1['Trainer'].unique()

array(['Priya S', 'Divya T', 'Arun K', 'Rahul M', 'Anjali V', 'Karthik N',
       'Suresh G', 'Meena J', '  Anjali V  ', 'Sneha R', 'Vikram P',
       '  Suresh G  ', '  Karthik N  ', '  Meena J  ', nan, '  Divya T  ',
       '  Arun K  ', '  Sneha R  ', '  Priya S  ', '  Rahul M  ',
       '  Vikram P  '], dtype=object)

In [67]:
df1['Trainer'] = df1['Trainer'].str.strip()

In [68]:
df1['Trainer'].isnull().sum()

1823

In [69]:
df1['Trainer'].fillna(method='pad', inplace=True)

In [70]:
df1.loc[20]

MemberID                                M100020
FullName                             Rahul Nair
Email                 divya.patel20@example.com
Phone                                8236882013
Gender                                     Male
DateOfBirth                 1985-05-21 00:00:00
Age                                          41
City                                 Coimbatore
Branch                                Pune West
MembershipPlan                          Premium
JoinDate                    2023-12-19 00:00:00
MembershipStatus                         Active
MonthlyFee                               3999.0
DiscountPercent                              10
Revenue                                  3599.1
PaymentMethod                               EMI
WorkoutType                 Functional Training
Trainer                                Vikram P
AttendancePerMonth                            4
AvgWorkoutMinutes                            51
SessionsCompleted                            15
CustomerRating                              4.9
HeightCm                                  172.2
WeightKg                                   82.8
BMI                                       27.92
LeadSource                             Facebook
LastVisitDate                        2025-04-12
Name: 20, dtype: object

In [71]:
df1['AttendancePerMonth']

0         7
1         7
2         9
3        10
4        11
         ..
60895     6
60896    14
60897    14
60898    10
60899     9
Name: AttendancePerMonth, Length: 60900, dtype: int64

In [72]:
df1['AttendancePerMonth'].isnull().sum()

0

In [73]:
df1.describe()

,DateOfBirth,Age,JoinDate,MonthlyFee,DiscountPercent,Revenue,AttendancePerMonth,AvgWorkoutMinutes,SessionsCompleted,CustomerRating,BMI
count,60900,60900.000000,60651,60900.000000,60900.000000,60900.000000,60900.000000,60900.000000,60900.000000,58161.000000,60900.000000
mean,1984-01-16 19:17:47.586206912,42.132594,2023-11-14 17:55:57.471435008,2098.751002,10.048933,1840.855139,9.373005,55.288112,16.208489,2.989980,25.774453
min,1960-01-01 00:00:00,-3.000000,2021-01-01 00:00:00,-500.000000,0.000000,599.250000,-5.000000,-20.000000,-10.000000,-1.000000,-5.000000
25%,1972-01-26 00:00:00,30.000000,2022-06-08 00:00:00,1299.000000,0.000000,999.000000,7.000000,43.000000,13.000000,2.000000,21.660000
50%,1984-01-17 00:00:00,42.000000,2023-11-12 00:00:00,1999.000000,10.000000,1599.000000,9.000000,55.000000,16.000000,3.000000,25.420000
75%,1995-12-25 00:00:00,54.000000,2025-04-15 00:00:00,2999.000000,20.000000,2499.000000,11.000000,67.000000,19.000000,4.000000,29.480000
max,2007-12-31 00:00:00,150.000000,2028-01-01 00:00:00,250000.000000,250.000000,3999.000000,300.000000,999.000000,999.000000,10.000000,120.000000
std,NaN,13.955705,NaN,3878.929776,12.254823,948.350101,6.414239,23.118364,14.601437,1.160805,6.150517

In [74]:
df1['AttendancePerMonth'] = df1["AttendancePerMonth"].apply(lambda x : abs(x) if x < 0 else x)

In [75]:
df1['AttendancePerMonth'].min()

0

In [76]:
df1['MemberID'].duplicated().sum()

870

In [77]:
df1 = df1.drop_duplicates(subset='MemberID', keep='last')

In [78]:
df1.head(30)

,MemberID,FullName,Email,Phone,Gender,DateOfBirth,Age,City,Branch,MembershipPlan,...,Trainer,AttendancePerMonth,AvgWorkoutMinutes,SessionsCompleted,CustomerRating,HeightCm,WeightKg,BMI,LeadSource,LastVisitDate
0,M100000,Sneha Kumar,rahul.rao0@example.com,8555928865,Male,1971-02-17,55,Tiruchirappalli,Madurai South,Platinum,...,Priya S,7,44,21,4.8,157.5,87.3,35.19,Walk-in,2023-11-26
1,M100001,Suresh Patel,suresh.iyer1@example.com,8572454672,Male,1983-11-18,42,Coimbatore,Pune West,Basic,...,Divya T,7,50,9,1.4,184.7,44.3,12.99,Google Ads,2027-03-15
2,M100002,Divya Reddy,suresh.das2@example.com,8641006265,Female,2002-02-03,24,Visakhapatnam,Bangalore East,Student,...,Arun K,9,67,26,4.4,159.2,34.0,13.42,Referral,2025-07-23
3,M100003,Sneha Rao,karthik.kumar3@example.com,8731328501,Female,1998-02-23,28,Delhi,Mumbai Central,Platinum,...,Rahul M,10,73,17,1.2,165.4,65.5,23.94,Referral,2025-04-27
4,M100004,Swathi Sharma,karthik.das4@example.com,9566756567,Female,1988-05-16,38,Mysuru,Vellore North,Family,...,Anjali V,11,54,15,1.4,165.5,77.3,28.22,Corporate,2028-06-04
5,M100005,Aditya Nair,pooja.kumar5@example.com,Not Given,Male,1997-04-12,29,Madurai,Mumbai Central,Basic,...,Karthik N,11,22,12,1.3,159.9,95.4,37.31,Google Ads,2022-06-02
6,M100006,Priya Kumar,pooja.iyer6@example.com,6825018365,Male,1968-06-16,58,Mysuru,Madurai South,Student,...,Arun K,13,40,-10,3.1,186.1,82.3,23.76,Partner,2025-11-13
7,M100007,Rahul Patel,neha.sharma7@example.com,9985354754,Female,1977-01-18,49,Delhi,Coimbatore Main,Premium,...,Karthik N,7,53,14,2.1,158.7,87.8,34.86,Facebook,2024-07-18
9,M100009,Ishita Kumar,sneha.reddy9@example.com,9115346340,Female,1962-07-06,64,Salem,Bangalore East,Platinum,...,Divya T,7,69,19,4.8,165.0,71.9,26.41,Partner,2022-01-21
10,M100010,Swathi Patel,rahul.das10@example.com,6636805043,Female,1991-05-09,35,Vellore,Chennai Central,Gold,...,Suresh G,10,63,18,2.4,165.0,75.6,27.77,Google Ads,2027-03-09
11,M100011,Swathi Nair,suresh.kumar11@example.com,8687288098,Male,2000-04-03,26,Vijayawada,Vellore North,Gold,...,Meena J,5,61,12,2.0,161.5,NaN,27.72,Corporate,2023-07-10
12,M100012,Divya Gupta,kavya.nair12@example.com,7179911827,Male,1965-08-29,61,Delhi,Chennai Central,Student,...,Anjali V,3,34,17,1.2,174.8,95.7,31.32,Instagram,2026-11-14
13,M100013,Aditya Singh,ravi.gupta13@example.com,9600948232,Female,1998-07-14,28,Delhi,Vellore North,Gold,...,Priya S,6,53,10,3.6,187.8,70.0,19.85,Corporate,2027-04-14
14,M100014,Arun Mehta,divya.joshi14@example.com,9272069267,not Given,1966-08-01,60,Coimbatore,Delhi NCR,Student,...,Sneha R,11,65,21,4.4,162.4,32.6,12.36,Walk-in,2024-12-04
15,M100015,Anjali Joshi,NaN,9409133806,Male,1984-07-16,42,Coimbatore,Kochi Marine,Student,...,Priya S,4,70,14,2.4,165.0,₹50.80,18.66,Facebook,2026-03-15
16,M100016,Pooja Iyer,meena.verma16@example.com,8440228303,Male,1998-01-27,28,Salem,Madurai South,Platinum,...,Vikram P,14,59,11,NaN,182.6,80.0,23.99,Facebook,2024-04-18
17,M100017,Suresh Reddy,arun.gupta17@example.com,9449234723,Male,1999-05-29,27,Bengaluru,Mumbai Central,Premium,...,Vikram P,7,56,24,4.1,156.8,53.7,21.84,Referral,2023-10-04
18,M100018,Karthik Mehta,swathi.mishra18@example.com,7082546788,Male,2002-03-14,24,Delhi,Kochi Marine,Student,...,Meena J,8,31,11,4.0,160.2,72.0,28.05,Website,2023-10-30
19,M100019,Amit Sharma,anjali.singh19@example.com,Not Given,Other,2006-10-26,19,Tiruchirappalli,Bangalore East,Basic,...,Meena J,8,53,12,4.6,181.7,77.4,23.44,Facebook,NaN
20,M100020,Rahul Nair,divya.patel20@example.com,8236882013,Male,1985-05-21,41,Coimbatore,Pune West,Premium,...,Vikram P,4,51,15,4.9,172.2,82.8,27.92,Facebook,2025-04-12
21,M100021,Sneha Iyer,ravi.pillai21@example.com,8775836562,Female,2003-09-15,22,Bengaluru,Pune West,Gold,...,Priya S,6,46,14,4.0,159.4,76.0,29.91,Facebook,2027-12-19
22,M100022,Neha Verma,sneha.mishra22@example.com,8769999790,Male,1977-08-08,49,Pune,Coimbatore Main,Premium,...,Sneha R,9,71,16,4.0,174.2,62.4,20.56,Walk-in,NaN
23,M100023,Suresh Mehta,ravi.kumar23@example.com,8457048596,Female,1966-12-31,59,Delhi,Mumbai Central,Family,...,Meena J,11,35,12,4.5,152.6,32.4,13.91,Partner,2027-04-19
24,M100024,Priya Joshi,pooja.pillai24@example.com,7723226618,Non-binary,1963-12-28,62,Visakhapatnam,Bangalore East,Premium,...,Meena J,7,26,8,4.1,178.9,57.6,18.00,Partner,2022-05-30
25,M100025,Naveen Das,karthik.kumar25@example.com,9658304772,Female,1970-07-04,56,Vijayawada,Hyderabad Hub,Platinum,...,Anjali V,8,49,12,4.5,148.3,NaN,25.74,Walk-in,2023-09-06
26,M100026,Sneha Mishra,anjali.iyer26@example.com,6585172004,Female,1967-05-19,59,Kochi,Pune West,Family,...,Karthik N,8,61,10,2.7,157.8,74.1,29.76,Referral,2028-07-20
27,M100027,Ravi Sharma,swathi.pillai27@example.com,7013370892,Female,1972-05-08,54,Madurai,Hyderabad Hub,Gold,...,Divya T,12,69,22,3.6,171.7,47.3,16.04,Facebook,2027-05-03
28,M100028,Swathi Singh,divya.mishra28@example.com,8360374217,Male,1988-05-26,38,Kochi,Chennai Central,Basic,...,Karthik N,6,62,14,3.3,155.4,71.9,29.77,Referral,2027-05-17
29,M100029,Ishita Mishra,ravi.pillai29@example.com,9770970089,Male,1979-03-31,47,Pune,Coimbatore Main,Student,...,Sneha R,9,46,17,1.7,168.1,86.7,30.68,Instagram,2024-06-03
30,M100030,Neha Verma,ravi.mehta30@example.com,7894215184,Male,2004-09-27,21,Tiruchirappalli,Delhi NCR,Premium,...,Arun K,6,68,15,3.0,173.7,NaN,23.40,Referral,2026-10-27

In [79]:
import re 

email_pattern = r"^[A-Za-z0-9.]+@[A-Za-z]+\.[a-zA-Z]{2,}$"

In [80]:
# df1 = df1[df1['Email'].str.match(email_pattern, na=False)]

In [81]:
df1.duplicated().sum()

0

In [82]:
df1['Email'].apply(type).value_counts()

Email
<class 'str'>      58416
<class 'float'>     1614
Name: count, dtype: int64

In [83]:
def verify(val):
    if isinstance(val, float):
        print(val)

df1['Email'].apply(verify)

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

0        None
1        None
2        None
3        None
4        None
         ...
60895    None
60896    None
60897    None
60898    None
60899    None
Name: Email, Length: 60030, dtype: object

In [84]:
df1['Age'] = df1['Age'].clip(lower=0, upper=100)

In [85]:
df1.describe()

,DateOfBirth,Age,JoinDate,MonthlyFee,DiscountPercent,Revenue,AttendancePerMonth,AvgWorkoutMinutes,SessionsCompleted,CustomerRating,BMI
count,60030,60030.000000,59788,60030.000000,60030.000000,60030.000000,60030.000000,60030.000000,60030.000000,57331.000000,60030.000000
mean,1984-01-16 05:52:47.496251776,42.123921,2023-11-14 19:36:33.430119936,2100.503182,10.040063,1841.715616,9.372597,55.296418,16.208746,2.990002,25.777169
min,1960-01-01 00:00:00,0.000000,2021-01-01 00:00:00,-500.000000,0.000000,599.250000,0.000000,-20.000000,-10.000000,-1.000000,-5.000000
25%,1972-01-20 00:00:00,30.000000,2022-06-08 00:00:00,1299.000000,0.000000,999.000000,7.000000,43.000000,13.000000,2.000000,21.660000
50%,1984-01-19 00:00:00,42.000000,2023-11-12 00:00:00,1999.000000,10.000000,1599.000000,9.000000,55.000000,16.000000,3.000000,25.430000
75%,1995-12-24 00:00:00,54.000000,2025-04-15 00:00:00,2999.000000,20.000000,2499.000000,11.000000,67.000000,19.000000,4.000000,29.480000
max,2007-12-31 00:00:00,100.000000,2028-01-01 00:00:00,250000.000000,250.000000,3999.000000,300.000000,999.000000,999.000000,10.000000,120.000000
std,NaN,13.895838,NaN,3905.098968,12.241754,948.907545,6.326621,23.188361,14.698767,1.160785,6.141632

In [86]:
df1['BMI'] =df1['BMI'].apply(lambda x : abs(x) if x < 0 else x)

In [87]:
df1['MonthlyFee'] =df1['MonthlyFee'].apply(lambda x : abs(x) if x < 0 else x)

In [88]:
df1['AvgWorkoutMinutes'] =df1['AvgWorkoutMinutes'].apply(lambda x : abs(x) if x < 0 else x)

In [89]:
df1['SessionsCompleted'] =df1['SessionsCompleted'].apply(lambda x : abs(x) if x < 0 else x)

In [90]:
df1['CustomerRating'] =df1['CustomerRating'].apply(lambda x : abs(x) if x < 0 else x)

In [91]:
today = pd.Timestamp.today()

df1["JoinDate"] = df1['JoinDate'].apply(lambda x : x if x < today else pd.NaT)

In [92]:
df1['JoinDate'].apply(type).value_counts()

JoinDate
<class 'pandas._libs.tslibs.timestamps.Timestamp'>    59274
<class 'pandas._libs.tslibs.nattype.NaTType'>           756
Name: count, dtype: int64

In [93]:
df1['DateOfBirth'].apply(type).value_counts()

DateOfBirth
<class 'pandas._libs.tslibs.timestamps.Timestamp'>    60030
Name: count, dtype: int64

In [94]:
df1["AvgWorkoutMinutes"].isnull().sum()

0

In [95]:
df1['AvgWorkoutMinutes'].apply(type).value_counts()

AvgWorkoutMinutes
<class 'int'>    60030
Name: count, dtype: int64

In [96]:
df1['AvgWorkoutMinutes'].unique()

array([ 44,  50,  67,  73,  54,  22,  40,  53,  69,  63,  61,  34,  65,
        70,  59,  56,  31,  51,  46,  71,  35,  26,  49,  62,  68,  83,
        45,  32,  42,  60,  55,  38,  48,  43,  94,  52, 100,  39,  74,
        47,  79,  89,  57,  37,  15,  58,  76,  78,  77,  66,  91,  41,
        29,  84,  96,  36,  85, 107,  64,  33,  95,  75,  21,  72,  80,
        25,  24,  30,  10,  97,  17,  93,  13,  86,  14, 106,  81,  88,
        28,  87,  82, 101,  11,  18,  90, 110,  27, 109, 103, 113,  98,
        92, 104,   0,  12,  16,  99, 102,  20,  19,  23, 118, 105, 116,
       500, 999, 111, 114, 108, 115, 123, 120, 117, 119, 136, 112, 134,
       127, 122, 129])

In [97]:
df1['SessionsCompleted'].isnull().sum()

0

In [98]:
df1['SessionsCompleted'].apply(type).value_counts()

SessionsCompleted
<class 'int'>    60030
Name: count, dtype: int64

In [99]:
sd = df1['SessionsCompleted'].unique()

In [100]:
hd = df1[df1['SessionsCompleted'] >= 200].index

In [101]:
for i in hd:
    print(df1.loc[i])

MemberID                                    M101321
FullName                                Kavya Patel
Email                 naveen.pillai1321@example.com
Phone                                    9970994580
Gender                                       Female
DateOfBirth                     1977-02-04 00:00:00
Age                                              49
City                                          Salem
Branch                               Bangalore East
MembershipPlan                                 Gold
JoinDate                        2026-04-10 00:00:00
MembershipStatus                           Inactive
MonthlyFee                                   2499.0
DiscountPercent                                   5
Revenue                                     2374.05
PaymentMethod                            Debit card
WorkoutType                                 Pilates
Trainer                                     Divya T
AttendancePerMonth                               13
AvgWorkoutMinutes                                52
SessionsCompleted                               200
CustomerRating                                  3.7
HeightCm                                      166.4
WeightKg                                       87.9
BMI                                           31.75
LeadSource                                Instagram
LastVisitDate                            2027-02-26
Name: 1321, dtype: object
MemberID                               M102538
FullName                            Neha Joshi
Email                 ravi.das2538@example.com
Phone                               6824190484
Gender                                    Male
DateOfBirth                2000-05-21 00:00:00
Age                                         26
City                                     Salem
Branch                           Hyderabad Hub
MembershipPlan                        Platinum
JoinDate                   2026-08-09 00:00:00
MembershipStatus                        Active
MonthlyFee                              2499.0
DiscountPercent                             10
Revenue                                 2249.1
PaymentMethod                              UPI
WorkoutType                           Strength
Trainer                                Divya T
AttendancePerMonth                           9
AvgWorkoutMinutes                           59
SessionsCompleted                          200
CustomerRating                             4.4
HeightCm                                 171.2
WeightKg                                  84.9
BMI                                      28.97
LeadSource                           Corporate
LastVisitDate                       2026-08-25
Name: 2538, dtype: object
MemberID                          M104362
FullName                     Anjali Singh
Email                                 NaN
Phone                           Not Given
Gender                             Female
DateOfBirth           1968-08-01 00:00:00
Age                                    58
City                            Bengaluru
Branch                      Madurai South
MembershipPlan                       Gold
JoinDate              2024-10-12 00:00:00
MembershipStatus                   Active
MonthlyFee                         1299.0
DiscountPercent                         0
Revenue                            1299.0
PaymentMethod                  Debit card
WorkoutType                      Strength
Trainer                          Anjali V
AttendancePerMonth                     15
AvgWorkoutMinutes                      83
SessionsCompleted                     999
CustomerRating                        4.1
HeightCm                            154.3
WeightKg                             88.9
BMI                                 37.34
LeadSource                      Instagram
LastVisitDate                  2026-09-14
Name: 4362, dtype: object
MemberID                                   M106611
FullName                              Kavya Pillai
Email                 ishita.patel6611@example.com
Phone                                   8206521041
Gender                                        Male
DateOfBirth                    1985-10-24 00:00:00
Age                                             40
City                                 Visakhapatnam
Branch                                Kochi Marine
MembershipPlan                             Premium
JoinDate                       2024-08-06 00:00:00
MembershipStatus                            Active
MonthlyFee                                   799.0
DiscountPercent                                  0
Revenue                                      799.0
PaymentMethod                               Wallet
WorkoutType                               CrossFit
Trainer                                   Vikram P
AttendancePerMonth                               5
AvgWorkoutMinutes                               70
SessionsCompleted                              999
CustomerRating                                 1.6
HeightCm                                     170.7
WeightKg                                      57.1
BMI                                           19.6
LeadSource                                Referral
LastVisitDate                           2026-09-16
Name: 6611, dtype: object
MemberID                                   M113419
FullName                              Aditya Kumar
Email                 karthik.rao13419@example.com
Phone                                   6655193886
Gender                                        Male
DateOfBirth                    1986-12-03 00:00:00
Age                                             39
City                                         Salem
Branch                             Coimbatore Main
MembershipPlan                               Basic
JoinDate                                       NaT
MembershipStatus                            Active
MonthlyFee                                  3999.0
DiscountPercent                                  0
Revenue                                     3999.0
PaymentMethod                               Wallet
WorkoutType                                  Zumba
Trainer                                    Rahul M
AttendancePerMonth                              11
AvgWorkoutMinutes                               39
SessionsCompleted                              200
CustomerRating                                 4.9
HeightCm                                     181.0
WeightKg                                      74.3
BMI                                          22.68
LeadSource                              Google Ads
LastVisitDate                           2027-09-03
Name: 13419, dtype: object
MemberID                                   M114680
FullName                                  Ravi Das
Email                 neha.sharma14680@example.com
Phone                                   7022076172
Gender                                        Male
DateOfBirth                    1965-01-10 00:00:00
Age                                             61
City                                         Salem
Branch                              Mumbai Central
MembershipPlan                            Platinum
JoinDate                       2021-02-01 00:00:00
MembershipStatus                            Frozen
MonthlyFee                                  1599.0
DiscountPercent                                 25
Revenue                                    1199.25
PaymentMethod                                  UPI
WorkoutType                                Pilates
Trainer                                    Divya T
AttendancePerMonth                              10
AvgWorkoutMinutes                               29
SessionsCompleted                              200
CustomerRating                                 2.8
HeightCm                                     144.8
WeightKg                                    ₹75.40
BMI                                          35.96
LeadSource                               Corporate
LastVisitDate                           2021-05-22
Name: 14680, dtype: object
MemberID                                    M116787
FullName                               Vikram Singh
Email                 vikram.gupta16787@example.com
Phone                                    6987000739
Gender                                       Female
DateOfBirth                     1978-05-30 00:00:00
Age                                              48
City                                         Mysuru
Branch                                Vellore North
MembershipPlan                              Premium
JoinDate                        2025-05-15 00:00:00
MembershipStatus                             Active
MonthlyFee                                   2499.0
DiscountPercent                                  20
Revenue                                      1999.2
PaymentMethod                           Net banking
WorkoutType                                   Zumba
Trainer                                   Karthik N
AttendancePerMonth                                7
AvgWorkoutMinutes                                40
SessionsCompleted                               200
CustomerRating                                  3.8
HeightCm                                      163.2
WeightKg                                       64.8
BMI                                           24.33
LeadSource                                Corporate
LastVisitDate                            2026-04-22
Name: 16787, dtype: object
MemberID                                    M120675
FullName                                Priya Joshi
Email                 ishita.joshi20675@example.com
Phone                                    6027615753
Gender                                         Male
DateOfBirth                     1970-09-21 00:00:00
Age                                              55
City                                         Mumbai
Branch                                    Delhi NCR
MembershipPlan                                Basic
JoinDate                        2023-11-06 00:00:00
MembershipStatus                             Active
MonthlyFee                                   3999.0
DiscountPercent                                  10
Revenue                                      3599.1
PaymentMethod                           Net banking
WorkoutType                                Strength
Trainer                                    Anjali V
AttendancePerMonth                                8
AvgWorkoutMinutes                                78
SessionsCompleted                               200
CustomerRating                                  2.6
HeightCm                                      167.8
WeightKg                                       94.7
BMI                                           33.63
LeadSource                                Instagram
LastVisitDate                            2026-08-10
Name: 20675, dtype: object
MemberID                                  M121221
FullName                              Anjali Iyer
Email                 neha.kumar21221@example.com
Phone                                  9122386602
Gender                                       Male
DateOfBirth                   2000-03-27 00:00:00
Age                                            26
City                              Tiruchirappalli
Branch                                  Delhi NCR
MembershipPlan                             Family
JoinDate                      2026-02-22 00:00:00
MembershipStatus                           Active
MonthlyFee                                  799.0
DiscountPercent                                10
Revenue                                     719.1
PaymentMethod                                 UPI
WorkoutType                                Cardio
Trainer                                   Rahul M
AttendancePerMonth                              0
AvgWorkoutMinutes                              48
SessionsCompleted                             200
CustomerRating                                2.4
HeightCm                                  ₹151.90
WeightKg                                     68.7
BMI                                         29.77
LeadSource                                Walk-in
LastVisitDate                          2028-12-11
Name: 21221, dtype: object
MemberID                                    M123659
FullName                                Aditya Iyer
Email                 pooja.mishra23659@example.com
Phone                                    7513796029
Gender                                         Male
DateOfBirth                     1977-02-23 00:00:00
Age                                              49
City                                      Hyderabad
Branch                                Madurai South
MembershipPlan                               Family
JoinDate                        2022-07-06 00:00:00
MembershipStatus                             Frozen
MonthlyFee                                   1599.0
DiscountPercent                                  25
Revenue                                     1199.25
PaymentMethod                                   UPI
WorkoutType                                   Zumba
Trainer                                     Meena J
AttendancePerMonth                                7
AvgWorkoutMinutes                                54
SessionsCompleted                               999
CustomerRating                                  4.2
HeightCm                                      177.2
WeightKg                                       63.2
BMI                                           20.13
LeadSource                                 Facebook
LastVisitDate                            2025-07-02
Name: 23659, dtype: object
MemberID                                  M124781
FullName                                Rahul Rao
Email                 arun.verma24781@example.com
Phone                                   Not Given
Gender                                     Female
DateOfBirth                   1979-10-17 00:00:00
Age                                            46
City                                      Madurai
Branch                               Kochi Marine
MembershipPlan                              Basic
JoinDate                      2025-04-13 00:00:00
MembershipStatus                         Inactive
MonthlyFee                                 1999.0
DiscountPercent                                 0
Revenue                                    1999.0
PaymentMethod                         Credit card
WorkoutType                                Cardio
Trainer                                 Karthik N
AttendancePerMonth                             10
AvgWorkoutMinutes                              60
SessionsCompleted                             999
CustomerRating                                2.8
HeightCm                                    166.3
WeightKg                                     80.0
BMI                                         28.93
LeadSource                                Website
LastVisitDate                                 NaN
Name: 24781, dtype: object
MemberID                                   M125145
FullName                               Kavya Kumar
Email                 manoj.singh25145@example.com
Phone                                   9816847713
Gender                                      Female
DateOfBirth                    2006-09-30 00:00:00
Age                                             19
City                                         Delhi
Branch                               Madurai South
MembershipPlan                             Student
JoinDate                       2024-01-03 00:00:00
MembershipStatus                         Cancelled
MonthlyFee                                   999.0
DiscountPercent                                  5
Revenue                                     949.05
PaymentMethod                                 Cash
WorkoutType                                Pilates
Trainer                                    Sneha R
AttendancePerMonth                               8
AvgWorkoutMinutes                               46
SessionsCompleted                              999
CustomerRating                                 2.9
HeightCm                                     174.1
WeightKg                                      93.8
BMI                                          30.95
LeadSource                                 Website
LastVisitDate                           2025-01-05
Name: 25145, dtype: object
MemberID                                  M129756
FullName                              Divya Verma
Email                 amit.patel29756@example.com
Phone                                  7586664609
Gender                                     Female
DateOfBirth                   1994-08-30 00:00:00
Age                                            32
City                                        Kochi
Branch                              Madurai South
MembershipPlan                               Gold
JoinDate                      2023-11-04 00:00:00
MembershipStatus                           Active
MonthlyFee                                 2999.0
DiscountPercent                                 0
Revenue                                    2999.0
PaymentMethod                         Net banking
WorkoutType                                Cardio
Trainer                                   Meena J
AttendancePerMonth                              4
AvgWorkoutMinutes                              67
SessionsCompleted                             999
CustomerRating                                4.3
HeightCm                                    154.4
WeightKg                                     58.5
BMI                                         24.54
LeadSource                                Walk-in
LastVisitDate                          2027-02-04
Name: 29756, dtype: object
MemberID                                   M131520
FullName                             Vikram Pillai
Email                 pooja.joshi31520@example.com
Phone                                   7580790201
Gender                                        Male
DateOfBirth                    1980-06-20 00:00:00
Age                                             46
City                                     Bengaluru
Branch                               Hyderabad Hub
MembershipPlan                            Platinum
JoinDate                       2021-01-30 00:00:00
MembershipStatus                           Pending
MonthlyFee                                  2999.0
DiscountPercent                                 15
Revenue                                    2549.15
PaymentMethod                                  UPI
WorkoutType                               Swimming
Trainer                                   Anjali V
AttendancePerMonth                              10
AvgWorkoutMinutes                               56
SessionsCompleted                              999
CustomerRating                                 4.3
HeightCm                                     173.4
WeightKg                                      98.4
BMI                                          32.73
LeadSource                                 Website
LastVisitDate                           2023-07-12
Name: 31520, dtype: object
MemberID                                    M133410
FullName                                Meena Reddy
Email                 suresh.verma33410@example.com
Phone                                    9685694591
Gender                                         Male
DateOfBirth                     1986-08-21 00:00:00
Age                                              40
City                                     Coimbatore
Branch                              Coimbatore Main
MembershipPlan                                Basic
JoinDate                        2023-02-11 00:00:00
MembershipStatus                             Active

In [102]:
sd = sd[sd < 200]

In [103]:
mm = round(np.mean(sd))

In [104]:
df1['SessionsCompleted'] = df1['SessionsCompleted'].apply(lambda x :x if x < 200 else mm)

In [105]:
df1['SessionsCompleted'].unique()

array([21,  9, 26, 17, 15, 12, 10, 14, 19, 18, 11, 24, 16,  8, 22, 20, 13,
       23, 25, 28, 27,  7,  5,  6, 38, 29, 35,  4, 30, 33, 34,  3, 32, 31])

In [106]:
df1['SessionsCompleted'] = df1['SessionsCompleted'].apply(lambda x : mm if x == 19.56 else x).astype(int)

In [107]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60030 entries, 0 to 60899
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   MemberID            60030 non-null  object
 1   FullName            60030 non-null  object
 2   Email               58416 non-null  object
 3   Phone               60030 non-null  object
 4   Gender              60030 non-null  object
 5   DateOfBirth         60030 non-null  datetime64[ns]
 6   Age                 60030 non-null  int64
 7   City                60030 non-null  object
 8   Branch              60030 non-null  object
 9   MembershipPlan      60030 non-null  object
 10  JoinDate            59274 non-null  datetime64[ns]
 11  MembershipStatus    60030 non-null  object
 12  MonthlyFee          60030 non-null  float64
 13  DiscountPercent     60030 non-null  int64
 14  Revenue             60030 non-null  float64
 15  PaymentMethod       58911 non-null  object
 16  WorkoutType         60030 non-null  object
 17  Trainer             60030 non-null  object
 18  AttendancePerMonth  60030 non-null  int64
 19  AvgWorkoutMinutes   60030 non-null  int64
 20  SessionsCompleted   60030 non-null  int64
 21  CustomerRating      57331 non-null  float64
 22  HeightCm            58832 non-null  object
 23  WeightKg            58531 non-null  object
 24  BMI                 60030 non-null  float64
 25  LeadSource          60030 non-null  object
 26  LastVisitDate       57672 non-null  object
dtypes: datetime64[ns](2), float64(4), int64(5), object(16)
memory usage: 14.8+ MB

In [145]:
df1.describe()

,DateOfBirth,Age,JoinDate,MonthlyFee,DiscountPercent,Revenue,AttendancePerMonth,AvgWorkoutMinutes,SessionsCompleted,CustomerRating,HeightCm,WeightKg,BMI
count,60030,60030.000000,59274,60030.000000,60030.000000,60030.000000,60030.000000,60030.000000,60030.000000,60030.000000,60030.000000,60030.000000,60030.000000
mean,1984-01-16 05:52:47.496251776,42.123921,2023-11-01 20:58:15.414515712,2100.703082,10.040063,1841.715616,9.372597,55.304414,15.980726,2.990818,168.011598,71.958461,25.761924
min,1960-01-01 00:00:00,0.000000,2021-01-01 00:00:00,0.000000,0.000000,599.250000,0.000000,0.000000,3.000000,0.000000,128.000000,10.800000,3.940000
25%,1972-01-20 00:00:00,30.000000,2022-06-04 00:00:00,1299.000000,0.000000,999.000000,7.000000,43.000000,13.000000,2.000000,161.400000,62.800000,21.760000
50%,1984-01-19 00:00:00,42.000000,2023-11-03 00:00:00,1999.000000,10.000000,1599.000000,9.000000,55.000000,16.000000,3.000000,168.000000,72.000000,25.440000
75%,1995-12-24 00:00:00,54.000000,2025-04-02 00:00:00,2999.000000,20.000000,2499.000000,11.000000,67.000000,19.000000,3.900000,174.600000,81.100000,29.410000
max,2007-12-31 00:00:00,100.000000,2026-09-01 00:00:00,250000.000000,250.000000,3999.000000,300.000000,999.000000,38.000000,10.000000,213.600000,127.700000,59.340000
std,NaN,13.895838,NaN,3904.991436,12.241754,948.907545,6.326621,23.169284,4.006709,1.133424,9.880721,13.834976,5.869783

In [109]:
df1['CustomerRating'].isnull().sum()

2699

In [110]:
np.mean(df1['CustomerRating'])

2.9903856552301544

In [111]:
df1['CustomerRating'].fillna(3, inplace=True)

In [112]:
df1[['HeightCm','WeightKg']]

      HeightCm WeightKg
0        157.5     87.3
1        184.7     44.3
2        159.2     34.0
3        165.4     65.5
4        165.5     77.3
...        ...      ...
60895    177.9     55.2
60896    182.1     58.7
60897  ₹175.40     68.8
60898    167.7     55.9
60899    199.4     48.7

[60030 rows x 2 columns]

In [113]:
df1["HeightCm"] = df1["HeightCm"].str.replace('₹', "", regex=False).str.replace(',','', regex=True).astype(float)

In [114]:
df1["WeightKg"] = df1["WeightKg"].str.replace('₹', "", regex=False).str.replace(',','', regex=True).astype(float)

In [115]:
df1[ 'WeightKg'] = df1[ 'WeightKg'].apply(lambda x : abs(x) if x < 0 else x)

In [116]:
df1['HeightCm'] = df1['HeightCm'].apply(lambda x : abs(x) if x < 0 else x)

In [117]:
hd = np.sort(df1['HeightCm'].unique())

In [126]:
wd = np.sort(df1['WeightKg'].unique())

In [120]:
hd

array([  0. ,  10. ,  20. , 128. , 130.1, 130.2, 130.6, 130.9, 131. ,
       131.1, 131.4, 131.7, 132.4, 132.7, 133.4, 133.7, 133.8, 134. ,
       134.2, 134.4, 134.5, 134.8, 134.9, 135. , 135.1, 135.2, 135.3,
       135.4, 135.5, 135.6, 135.7, 135.8, 136. , 136.1, 136.4, 136.5,
       136.7, 136.8, 136.9, 137. , 137.1, 137.2, 137.3, 137.4, 137.6,
       137.7, 137.8, 138. , 138.1, 138.2, 138.3, 138.4, 138.5, 138.7,
       138.8, 138.9, 139. , 139.1, 139.4, 139.5, 139.6, 139.7, 139.8,
       139.9, 140. , 140.1, 140.2, 140.3, 140.4, 140.5, 140.6, 140.7,
       140.8, 140.9, 141. , 141.1, 141.2, 141.3, 141.4, 141.5, 141.6,
       141.7, 141.8, 141.9, 142. , 142.1, 142.2, 142.3, 142.4, 142.5,
       142.6, 142.7, 142.8, 142.9, 143. , 143.1, 143.2, 143.3, 143.4,
       143.5, 143.6, 143.7, 143.8, 143.9, 144. , 144.1, 144.2, 144.3,
       144.4, 144.5, 144.6, 144.7, 144.8, 144.9, 145. , 145.1, 145.2,
       145.3, 145.4, 145.5, 145.6, 145.7, 145.8, 145.9, 146. , 146.1,
       146.2, 146.3, 146.4, 146.5, 146.6, 146.7, 146.8, 146.9, 147. ,
       147.1, 147.2, 147.3, 147.4, 147.5, 147.6, 147.7, 147.8, 147.9,
       148. , 148.1, 148.2, 148.3, 148.4, 148.5, 148.6, 148.7, 148.8,
       148.9, 149. , 149.1, 149.2, 149.3, 149.4, 149.5, 149.6, 149.7,
       149.8, 149.9, 150. , 150.1, 150.2, 150.3, 150.4, 150.5, 150.6,
       150.7, 150.8, 150.9, 151. , 151.1, 151.2, 151.3, 151.4, 151.5,
       151.6, 151.7, 151.8, 151.9, 152. , 152.1, 152.2, 152.3, 152.4,
       152.5, 152.6, 152.7, 152.8, 152.9, 153. , 153.1, 153.2, 153.3,
       153.4, 153.5, 153.6, 153.7, 153.8, 153.9, 154. , 154.1, 154.2,
       154.3, 154.4, 154.5, 154.6, 154.7, 154.8, 154.9, 155. , 155.1,
       155.2, 155.3, 155.4, 155.5, 155.6, 155.7, 155.8, 155.9, 156. ,
       156.1, 156.2, 156.3, 156.4, 156.5, 156.6, 156.7, 156.8, 156.9,
       157. , 157.1, 157.2, 157.3, 157.4, 157.5, 157.6, 157.7, 157.8,
       157.9, 158. , 158.1, 158.2, 158.3, 158.4, 158.5, 158.6, 158.7,
       158.8, 158.9, 159. , 159.1, 159.2, 159.3, 159.4, 159.5, 159.6,
       159.7, 159.8, 159.9, 160. , 160.1, 160.2, 160.3, 160.4, 160.5,
       160.6, 160.7, 160.8, 160.9, 161. , 161.1, 161.2, 161.3, 161.4,
       161.5, 161.6, 161.7, 161.8, 161.9, 162. , 162.1, 162.2, 162.3,
       162.4, 162.5, 162.6, 162.7, 162.8, 162.9, 163. , 163.1, 163.2,
       163.3, 163.4, 163.5, 163.6, 163.7, 163.8, 163.9, 164. , 164.1,
       164.2, 164.3, 164.4, 164.5, 164.6, 164.7, 164.8, 164.9, 165. ,
       165.1, 165.2, 165.3, 165.4, 165.5, 165.6, 165.7, 165.8, 165.9,
       166. , 166.1, 166.2, 166.3, 166.4, 166.5, 166.6, 166.7, 166.8,
       166.9, 167. , 167.1, 167.2, 167.3, 167.4, 167.5, 167.6, 167.7,
       167.8, 167.9, 168. , 168.1, 168.2, 168.3, 168.4, 168.5, 168.6,
       168.7, 168.8, 168.9, 169. , 169.1, 169.2, 169.3, 169.4, 169.5,
       169.6, 169.7, 169.8, 169.9, 170. , 170.1, 170.2, 170.3, 170.4,
       170.5, 170.6, 170.7, 170.8, 170.9, 171. , 171.1, 171.2, 171.3,
       171.4, 171.5, 171.6, 171.7, 171.8, 171.9, 172. , 172.1, 172.2,
       172.3, 172.4, 172.5, 172.6, 172.7, 172.8, 172.9, 173. , 173.1,
       173.2, 173.3, 173.4, 173.5, 173.6, 173.7, 173.8, 173.9, 174. ,
       174.1, 174.2, 174.3, 174.4, 174.5, 174.6, 174.7, 174.8, 174.9,
       175. , 175.1, 175.2, 175.3, 175.4, 175.5, 175.6, 175.7, 175.8,
       175.9, 176. , 176.1, 176.2, 176.3, 176.4, 176.5, 176.6, 176.7,
       176.8, 176.9, 177. , 177.1, 177.2, 177.3, 177.4, 177.5, 177.6,
       177.7, 177.8, 177.9, 178. , 178.1, 178.2, 178.3, 178.4, 178.5,
       178.6, 178.7, 178.8, 178.9, 179. , 179.1, 179.2, 179.3, 179.4,
       179.5, 179.6, 179.7, 179.8, 179.9, 180. , 180.1, 180.2, 180.3,
       180.4, 180.5, 180.6, 180.7, 180.8, 180.9, 181. , 181.1, 181.2,
       181.3, 181.4, 181.5, 181.6, 181.7, 181.8, 181.9, 182. , 182.1,
       182.2, 182.3, 182.4, 182.5, 182.6, 182.7, 182.8, 182.9, 183. ,
       183.1, 183.2, 183.3, 183.4, 183.5, 183.6, 183.7, 183.8, 183.9,
       184. , 184.1, 184.2, 184.3, 184.4, 184.5, 184.6, 184.7, 184.8,
       184.9, 185. , 185.1, 185.2, 185.3, 185.4, 185.5, 185.6, 185.7,
       185.8, 185.9, 186. , 186.1, 186.2, 186.3, 186.4, 186.5, 186.6,
       186.7, 186.8, 186.9, 187. , 187.1, 187.2, 187.3, 187.4, 187.5,
       187.6, 187.7, 187.8, 187.9, 188. , 188.1, 188.2, 188.3, 188.4,
       188.5, 188.6, 188.7, 188.8, 188.9, 189. , 189.1, 189.2, 189.3,
       189.4, 189.5, 189.6, 189.7, 189.8, 189.9, 190. , 190.1, 190.2,
       190.3, 190.4, 190.5, 190.6, 190.7, 190.8, 190.9, 191. , 191.1,
       191.2, 191.3, 191.4, 191.5, 191.6, 191.7, 191.8, 191.9, 192. ,
       192.1, 192.2, 192.3, 192.4, 192.5, 192.6, 192.7, 192.8, 192.9,
       193. , 193.1, 193.2, 193.3, 193.4, 193.5, 193.6, 193.7, 193.8,
       193.9, 194. , 194.1, 194.2, 194.3, 194.4, 194.5, 194.6, 194.7,
       194.8, 194.9, 195. , 195.1, 195.2, 195.3, 195.4, 195.5, 195.6,
       195.7, 195.8, 195.9, 196. , 196.1, 196.2, 196.3, 196.4, 196.5,
       196.6, 196.7, 196.8, 196.9, 197. , 197.1, 197.2, 197.3, 197.4,
       197.5, 197.6, 197.8, 197.9, 198. , 198.1, 198.2, 198.4, 198.5,
       198.6, 198.7, 198.8, 198.9, 199.1, 199.2, 199.3, 199.4, 199.5,
       199.8, 199.9, 200. , 200.1, 200.2, 200.3, 200.4, 200.5, 200.6,
       200.8, 200.9, 201.2, 201.3, 201.8, 201.9, 202. , 202.3, 202.4,
       202.6, 203.5, 203.6, 203.8, 203.9, 204. , 204.2, 204.7, 204.9,
       205.1, 205.7, 210. , 213.6, 280. , 350. ,   nan])

In [122]:
hd = hd[hd < 280]
hd = hd[hd > 20]

In [123]:
hd

array([128. , 130.1, 130.2, 130.6, 130.9, 131. , 131.1, 131.4, 131.7,
       132.4, 132.7, 133.4, 133.7, 133.8, 134. , 134.2, 134.4, 134.5,
       134.8, 134.9, 135. , 135.1, 135.2, 135.3, 135.4, 135.5, 135.6,
       135.7, 135.8, 136. , 136.1, 136.4, 136.5, 136.7, 136.8, 136.9,
       137. , 137.1, 137.2, 137.3, 137.4, 137.6, 137.7, 137.8, 138. ,
       138.1, 138.2, 138.3, 138.4, 138.5, 138.7, 138.8, 138.9, 139. ,
       139.1, 139.4, 139.5, 139.6, 139.7, 139.8, 139.9, 140. , 140.1,
       140.2, 140.3, 140.4, 140.5, 140.6, 140.7, 140.8, 140.9, 141. ,
       141.1, 141.2, 141.3, 141.4, 141.5, 141.6, 141.7, 141.8, 141.9,
       142. , 142.1, 142.2, 142.3, 142.4, 142.5, 142.6, 142.7, 142.8,
       142.9, 143. , 143.1, 143.2, 143.3, 143.4, 143.5, 143.6, 143.7,
       143.8, 143.9, 144. , 144.1, 144.2, 144.3, 144.4, 144.5, 144.6,
       144.7, 144.8, 144.9, 145. , 145.1, 145.2, 145.3, 145.4, 145.5,
       145.6, 145.7, 145.8, 145.9, 146. , 146.1, 146.2, 146.3, 146.4,
       146.5, 146.6, 146.7, 146.8, 146.9, 147. , 147.1, 147.2, 147.3,
       147.4, 147.5, 147.6, 147.7, 147.8, 147.9, 148. , 148.1, 148.2,
       148.3, 148.4, 148.5, 148.6, 148.7, 148.8, 148.9, 149. , 149.1,
       149.2, 149.3, 149.4, 149.5, 149.6, 149.7, 149.8, 149.9, 150. ,
       150.1, 150.2, 150.3, 150.4, 150.5, 150.6, 150.7, 150.8, 150.9,
       151. , 151.1, 151.2, 151.3, 151.4, 151.5, 151.6, 151.7, 151.8,
       151.9, 152. , 152.1, 152.2, 152.3, 152.4, 152.5, 152.6, 152.7,
       152.8, 152.9, 153. , 153.1, 153.2, 153.3, 153.4, 153.5, 153.6,
       153.7, 153.8, 153.9, 154. , 154.1, 154.2, 154.3, 154.4, 154.5,
       154.6, 154.7, 154.8, 154.9, 155. , 155.1, 155.2, 155.3, 155.4,
       155.5, 155.6, 155.7, 155.8, 155.9, 156. , 156.1, 156.2, 156.3,
       156.4, 156.5, 156.6, 156.7, 156.8, 156.9, 157. , 157.1, 157.2,
       157.3, 157.4, 157.5, 157.6, 157.7, 157.8, 157.9, 158. , 158.1,
       158.2, 158.3, 158.4, 158.5, 158.6, 158.7, 158.8, 158.9, 159. ,
       159.1, 159.2, 159.3, 159.4, 159.5, 159.6, 159.7, 159.8, 159.9,
       160. , 160.1, 160.2, 160.3, 160.4, 160.5, 160.6, 160.7, 160.8,
       160.9, 161. , 161.1, 161.2, 161.3, 161.4, 161.5, 161.6, 161.7,
       161.8, 161.9, 162. , 162.1, 162.2, 162.3, 162.4, 162.5, 162.6,
       162.7, 162.8, 162.9, 163. , 163.1, 163.2, 163.3, 163.4, 163.5,
       163.6, 163.7, 163.8, 163.9, 164. , 164.1, 164.2, 164.3, 164.4,
       164.5, 164.6, 164.7, 164.8, 164.9, 165. , 165.1, 165.2, 165.3,
       165.4, 165.5, 165.6, 165.7, 165.8, 165.9, 166. , 166.1, 166.2,
       166.3, 166.4, 166.5, 166.6, 166.7, 166.8, 166.9, 167. , 167.1,
       167.2, 167.3, 167.4, 167.5, 167.6, 167.7, 167.8, 167.9, 168. ,
       168.1, 168.2, 168.3, 168.4, 168.5, 168.6, 168.7, 168.8, 168.9,
       169. , 169.1, 169.2, 169.3, 169.4, 169.5, 169.6, 169.7, 169.8,
       169.9, 170. , 170.1, 170.2, 170.3, 170.4, 170.5, 170.6, 170.7,
       170.8, 170.9, 171. , 171.1, 171.2, 171.3, 171.4, 171.5, 171.6,
       171.7, 171.8, 171.9, 172. , 172.1, 172.2, 172.3, 172.4, 172.5,
       172.6, 172.7, 172.8, 172.9, 173. , 173.1, 173.2, 173.3, 173.4,
       173.5, 173.6, 173.7, 173.8, 173.9, 174. , 174.1, 174.2, 174.3,
       174.4, 174.5, 174.6, 174.7, 174.8, 174.9, 175. , 175.1, 175.2,
       175.3, 175.4, 175.5, 175.6, 175.7, 175.8, 175.9, 176. , 176.1,
       176.2, 176.3, 176.4, 176.5, 176.6, 176.7, 176.8, 176.9, 177. ,
       177.1, 177.2, 177.3, 177.4, 177.5, 177.6, 177.7, 177.8, 177.9,
       178. , 178.1, 178.2, 178.3, 178.4, 178.5, 178.6, 178.7, 178.8,
       178.9, 179. , 179.1, 179.2, 179.3, 179.4, 179.5, 179.6, 179.7,
       179.8, 179.9, 180. , 180.1, 180.2, 180.3, 180.4, 180.5, 180.6,
       180.7, 180.8, 180.9, 181. , 181.1, 181.2, 181.3, 181.4, 181.5,
       181.6, 181.7, 181.8, 181.9, 182. , 182.1, 182.2, 182.3, 182.4,
       182.5, 182.6, 182.7, 182.8, 182.9, 183. , 183.1, 183.2, 183.3,
       183.4, 183.5, 183.6, 183.7, 183.8, 183.9, 184. , 184.1, 184.2,
       184.3, 184.4, 184.5, 184.6, 184.7, 184.8, 184.9, 185. , 185.1,
       185.2, 185.3, 185.4, 185.5, 185.6, 185.7, 185.8, 185.9, 186. ,
       186.1, 186.2, 186.3, 186.4, 186.5, 186.6, 186.7, 186.8, 186.9,
       187. , 187.1, 187.2, 187.3, 187.4, 187.5, 187.6, 187.7, 187.8,
       187.9, 188. , 188.1, 188.2, 188.3, 188.4, 188.5, 188.6, 188.7,
       188.8, 188.9, 189. , 189.1, 189.2, 189.3, 189.4, 189.5, 189.6,
       189.7, 189.8, 189.9, 190. , 190.1, 190.2, 190.3, 190.4, 190.5,
       190.6, 190.7, 190.8, 190.9, 191. , 191.1, 191.2, 191.3, 191.4,
       191.5, 191.6, 191.7, 191.8, 191.9, 192. , 192.1, 192.2, 192.3,
       192.4, 192.5, 192.6, 192.7, 192.8, 192.9, 193. , 193.1, 193.2,
       193.3, 193.4, 193.5, 193.6, 193.7, 193.8, 193.9, 194. , 194.1,
       194.2, 194.3, 194.4, 194.5, 194.6, 194.7, 194.8, 194.9, 195. ,
       195.1, 195.2, 195.3, 195.4, 195.5, 195.6, 195.7, 195.8, 195.9,
       196. , 196.1, 196.2, 196.3, 196.4, 196.5, 196.6, 196.7, 196.8,
       196.9, 197. , 197.1, 197.2, 197.3, 197.4, 197.5, 197.6, 197.8,
       197.9, 198. , 198.1, 198.2, 198.4, 198.5, 198.6, 198.7, 198.8,
       198.9, 199.1, 199.2, 199.3, 199.4, 199.5, 199.8, 199.9, 200. ,
       200.1, 200.2, 200.3, 200.4, 200.5, 200.6, 200.8, 200.9, 201.2,
       201.3, 201.8, 201.9, 202. , 202.3, 202.4, 202.6, 203.5, 203.6,
       203.8, 203.9, 204. , 204.2, 204.7, 204.9, 205.1, 205.7, 210. ,
       213.6])

In [124]:
wd

array([  0. ,   2. ,  10.8,  15.1,  17.8,  18.2,  19.9,  20. ,  20.5,
        20.8,  21.3,  21.6,  22.5,  23. ,  23.2,  23.5,  23.8,  23.9,
        24. ,  24.2,  24.7,  25. ,  25.1,  25.2,  25.5,  25.7,  25.8,
        25.9,  26. ,  26.1,  26.6,  26.7,  27. ,  27.2,  27.4,  27.6,
        27.9,  28. ,  28.1,  28.2,  28.4,  28.5,  28.7,  28.8,  28.9,
        29.1,  29.2,  29.3,  29.4,  29.5,  29.6,  29.7,  29.8,  29.9,
        30.1,  30.2,  30.3,  30.4,  30.5,  30.6,  30.7,  30.8,  30.9,
        31. ,  31.1,  31.2,  31.4,  31.5,  31.6,  31.7,  31.8,  31.9,
        32. ,  32.1,  32.2,  32.3,  32.4,  32.5,  32.6,  32.7,  32.8,
        32.9,  33. ,  33.1,  33.2,  33.3,  33.4,  33.5,  33.6,  33.7,
        33.8,  33.9,  34. ,  34.1,  34.2,  34.3,  34.4,  34.5,  34.6,
        34.7,  34.8,  34.9,  35. ,  35.1,  35.2,  35.3,  35.4,  35.5,
        35.6,  35.7,  35.8,  35.9,  36. ,  36.1,  36.2,  36.3,  36.4,
        36.5,  36.6,  36.7,  36.8,  36.9,  37. ,  37.1,  37.2,  37.3,
        37.4,  37.5,  37.6,  37.7,  37.8,  37.9,  38. ,  38.1,  38.2,
        38.3,  38.4,  38.5,  38.6,  38.7,  38.8,  38.9,  39. ,  39.1,
        39.2,  39.3,  39.4,  39.5,  39.6,  39.7,  39.8,  39.9,  40. ,
        40.1,  40.2,  40.3,  40.4,  40.5,  40.6,  40.7,  40.8,  40.9,
        41. ,  41.1,  41.2,  41.3,  41.4,  41.5,  41.6,  41.7,  41.8,
        41.9,  42. ,  42.1,  42.2,  42.3,  42.4,  42.5,  42.6,  42.7,
        42.8,  42.9,  43. ,  43.1,  43.2,  43.3,  43.4,  43.5,  43.6,
        43.7,  43.8,  43.9,  44. ,  44.1,  44.2,  44.3,  44.4,  44.5,
        44.6,  44.7,  44.8,  44.9,  45. ,  45.1,  45.2,  45.3,  45.4,
        45.5,  45.6,  45.7,  45.8,  45.9,  46. ,  46.1,  46.2,  46.3,
        46.4,  46.5,  46.6,  46.7,  46.8,  46.9,  47. ,  47.1,  47.2,
        47.3,  47.4,  47.5,  47.6,  47.7,  47.8,  47.9,  48. ,  48.1,
        48.2,  48.3,  48.4,  48.5,  48.6,  48.7,  48.8,  48.9,  49. ,
        49.1,  49.2,  49.3,  49.4,  49.5,  49.6,  49.7,  49.8,  49.9,
        50. ,  50.1,  50.2,  50.3,  50.4,  50.5,  50.6,  50.7,  50.8,
        50.9,  51. ,  51.1,  51.2,  51.3,  51.4,  51.5,  51.6,  51.7,
        51.8,  51.9,  52. ,  52.1,  52.2,  52.3,  52.4,  52.5,  52.6,
        52.7,  52.8,  52.9,  53. ,  53.1,  53.2,  53.3,  53.4,  53.5,
        53.6,  53.7,  53.8,  53.9,  54. ,  54.1,  54.2,  54.3,  54.4,
        54.5,  54.6,  54.7,  54.8,  54.9,  55. ,  55.1,  55.2,  55.3,
        55.4,  55.5,  55.6,  55.7,  55.8,  55.9,  56. ,  56.1,  56.2,
        56.3,  56.4,  56.5,  56.6,  56.7,  56.8,  56.9,  57. ,  57.1,
        57.2,  57.3,  57.4,  57.5,  57.6,  57.7,  57.8,  57.9,  58. ,
        58.1,  58.2,  58.3,  58.4,  58.5,  58.6,  58.7,  58.8,  58.9,
        59. ,  59.1,  59.2,  59.3,  59.4,  59.5,  59.6,  59.7,  59.8,
        59.9,  60. ,  60.1,  60.2,  60.3,  60.4,  60.5,  60.6,  60.7,
        60.8,  60.9,  61. ,  61.1,  61.2,  61.3,  61.4,  61.5,  61.6,
        61.7,  61.8,  61.9,  62. ,  62.1,  62.2,  62.3,  62.4,  62.5,
        62.6,  62.7,  62.8,  62.9,  63. ,  63.1,  63.2,  63.3,  63.4,
        63.5,  63.6,  63.7,  63.8,  63.9,  64. ,  64.1,  64.2,  64.3,
        64.4,  64.5,  64.6,  64.7,  64.8,  64.9,  65. ,  65.1,  65.2,
        65.3,  65.4,  65.5,  65.6,  65.7,  65.8,  65.9,  66. ,  66.1,
        66.2,  66.3,  66.4,  66.5,  66.6,  66.7,  66.8,  66.9,  67. ,
        67.1,  67.2,  67.3,  67.4,  67.5,  67.6,  67.7,  67.8,  67.9,
        68. ,  68.1,  68.2,  68.3,  68.4,  68.5,  68.6,  68.7,  68.8,
        68.9,  69. ,  69.1,  69.2,  69.3,  69.4,  69.5,  69.6,  69.7,
        69.8,  69.9,  70. ,  70.1,  70.2,  70.3,  70.4,  70.5,  70.6,
        70.7,  70.8,  70.9,  71. ,  71.1,  71.2,  71.3,  71.4,  71.5,
        71.6,  71.7,  71.8,  71.9,  72. ,  72.1,  72.2,  72.3,  72.4,
        72.5,  72.6,  72.7,  72.8,  72.9,  73. ,  73.1,  73.2,  73.3,
        73.4,  73.5,  73.6,  73.7,  73.8,  73.9,  74. ,  74.1,  74.2,
        74.3,  74.4,  74.5,  74.6,  74.7,  74.8,  74.9,  75. ,  75.1,
        75.2,  75.3,  75.4,  75.5,  75.6,  75.7,  75.8,  75.9,  76. ,
        76.1,  76.2,  76.3,  76.4,  76.5,  76.6,  76.7,  76.8,  76.9,
        77. ,  77.1,  77.2,  77.3,  77.4,  77.5,  77.6,  77.7,  77.8,
        77.9,  78. ,  78.1,  78.2,  78.3,  78.4,  78.5,  78.6,  78.7,
        78.8,  78.9,  79. ,  79.1,  79.2,  79.3,  79.4,  79.5,  79.6,
        79.7,  79.8,  79.9,  80. ,  80.1,  80.2,  80.3,  80.4,  80.5,
        80.6,  80.7,  80.8,  80.9,  81. ,  81.1,  81.2,  81.3,  81.4,
        81.5,  81.6,  81.7,  81.8,  81.9,  82. ,  82.1,  82.2,  82.3,
        82.4,  82.5,  82.6,  82.7,  82.8,  82.9,  83. ,  83.1,  83.2,
        83.3,  83.4,  83.5,  83.6,  83.7,  83.8,  83.9,  84. ,  84.1,
        84.2,  84.3,  84.4,  84.5,  84.6,  84.7,  84.8,  84.9,  85. ,
        85.1,  85.2,  85.3,  85.4,  85.5,  85.6,  85.7,  85.8,  85.9,
        86. ,  86.1,  86.2,  86.3,  86.4,  86.5,  86.6,  86.7,  86.8,
        86.9,  87. ,  87.1,  87.2,  87.3,  87.4,  87.5,  87.6,  87.7,
        87.8,  87.9,  88. ,  88.1,  88.2,  88.3,  88.4,  88.5,  88.6,
        88.7,  88.8,  88.9,  89. ,  89.1,  89.2,  89.3,  89.4,  89.5,
        89.6,  89.7,  89.8,  89.9,  90. ,  90.1,  90.2,  90.3,  90.4,
        90.5,  90.6,  90.7,  90.8,  90.9,  91. ,  91.1,  91.2,  91.3,
        91.4,  91.5,  91.6,  91.7,  91.8,  91.9,  92. ,  92.1,  92.2,
        92.3,  92.4,  92.5,  92.6,  92.7,  92.8,  92.9,  93. ,  93.1,
        93.2,  93.3,  93.4,  93.5,  93.6,  93.7,  93.8,  93.9,  94. ,
        94.1,  94.2,  94.3,  94.4,  94.5,  94.6,  94.7,  94.8,  94.9,
        95. ,  95.1,  95.2,  95.3,  95.4,  95.5,  95.6,  95.7,  95.8,
        95.9,  96. ,  96.1,  96.2,  96.3,  96.4,  96.5,  96.6,  96.7,
        96.8,  96.9,  97. ,  97.1,  97.2,  97.3,  97.4,  97.5,  97.6,
        97.7,  97.8,  97.9,  98. ,  98.1,  98.2,  98.3,  98.4,  98.5,
        98.6,  98.7,  98.8,  98.9,  99. ,  99.1,  99.2,  99.3,  99.4,
        99.5,  99.6,  99.7,  99.8,  99.9, 100. , 100.1, 100.2, 100.3,
       100.4, 100.5, 100.6, 100.7, 100.8, 100.9, 101. , 101.1, 101.2,
       101.3, 101.4, 101.5, 101.6, 101.7, 101.8, 101.9, 102. , 102.1,
       102.2, 102.3, 102.4, 102.5, 102.6, 102.7, 102.8, 102.9, 103. ,
       103.1, 103.2, 103.3, 103.4, 103.5, 103.6, 103.7, 103.8, 103.9,
       104. , 104.1, 104.2, 104.3, 104.4, 104.5, 104.6, 104.7, 104.8,
       104.9, 105. , 105.1, 105.2, 105.3, 105.4, 105.5, 105.6, 105.7,
       105.8, 105.9, 106. , 106.1, 106.2, 106.3, 106.4, 106.5, 106.6,
       106.7, 106.8, 106.9, 107. , 107.1, 107.2, 107.3, 107.4, 107.5,
       107.6, 107.7, 107.8, 107.9, 108. , 108.1, 108.2, 108.3, 108.4,
       108.5, 108.6, 108.7, 108.8, 108.9, 109. , 109.1, 109.2, 109.3,
       109.4, 109.5, 109.6, 109.7, 109.8, 109.9, 110. , 110.1, 110.2,
       110.3, 110.4, 110.5, 110.6, 110.7, 110.8, 110.9, 111. , 111.1,
       111.2, 111.3, 111.4, 111.5, 111.6, 111.7, 111.8, 111.9, 112. ,
       112.1, 112.2, 112.3, 112.4, 112.5, 112.6, 112.9, 113. , 113.1,
       113.2, 113.3, 113.4, 113.5, 113.6, 113.7, 113.8, 114. , 114.1,
       114.2, 114.3, 114.8, 114.9, 115. , 115.2, 115.3, 115.6, 116. ,
       116.1, 116.5, 116.7, 116.9, 117.2, 117.3, 117.5, 117.6, 117.9,
       118. , 118.2, 118.4, 118.8, 119.8, 120.4, 120.5, 120.8, 120.9,
       121.2, 121.3, 121.6, 121.9, 122. , 122.3, 122.5, 122.6, 122.7,
       122.8, 123. , 123.1, 123.2, 124.2, 125. , 127.7, 350. , 500. ,
         nan])

In [127]:
wd = wd[wd < 350]
wd = wd[wd > 2]

In [128]:
wd

array([ 10.8,  15.1,  17.8,  18.2,  19.9,  20. ,  20.5,  20.8,  21.3,
        21.6,  22.5,  23. ,  23.2,  23.5,  23.8,  23.9,  24. ,  24.2,
        24.7,  25. ,  25.1,  25.2,  25.5,  25.7,  25.8,  25.9,  26. ,
        26.1,  26.6,  26.7,  27. ,  27.2,  27.4,  27.6,  27.9,  28. ,
        28.1,  28.2,  28.4,  28.5,  28.7,  28.8,  28.9,  29.1,  29.2,
        29.3,  29.4,  29.5,  29.6,  29.7,  29.8,  29.9,  30.1,  30.2,
        30.3,  30.4,  30.5,  30.6,  30.7,  30.8,  30.9,  31. ,  31.1,
        31.2,  31.4,  31.5,  31.6,  31.7,  31.8,  31.9,  32. ,  32.1,
        32.2,  32.3,  32.4,  32.5,  32.6,  32.7,  32.8,  32.9,  33. ,
        33.1,  33.2,  33.3,  33.4,  33.5,  33.6,  33.7,  33.8,  33.9,
        34. ,  34.1,  34.2,  34.3,  34.4,  34.5,  34.6,  34.7,  34.8,
        34.9,  35. ,  35.1,  35.2,  35.3,  35.4,  35.5,  35.6,  35.7,
        35.8,  35.9,  36. ,  36.1,  36.2,  36.3,  36.4,  36.5,  36.6,
        36.7,  36.8,  36.9,  37. ,  37.1,  37.2,  37.3,  37.4,  37.5,
        37.6,  37.7,  37.8,  37.9,  38. ,  38.1,  38.2,  38.3,  38.4,
        38.5,  38.6,  38.7,  38.8,  38.9,  39. ,  39.1,  39.2,  39.3,
        39.4,  39.5,  39.6,  39.7,  39.8,  39.9,  40. ,  40.1,  40.2,
        40.3,  40.4,  40.5,  40.6,  40.7,  40.8,  40.9,  41. ,  41.1,
        41.2,  41.3,  41.4,  41.5,  41.6,  41.7,  41.8,  41.9,  42. ,
        42.1,  42.2,  42.3,  42.4,  42.5,  42.6,  42.7,  42.8,  42.9,
        43. ,  43.1,  43.2,  43.3,  43.4,  43.5,  43.6,  43.7,  43.8,
        43.9,  44. ,  44.1,  44.2,  44.3,  44.4,  44.5,  44.6,  44.7,
        44.8,  44.9,  45. ,  45.1,  45.2,  45.3,  45.4,  45.5,  45.6,
        45.7,  45.8,  45.9,  46. ,  46.1,  46.2,  46.3,  46.4,  46.5,
        46.6,  46.7,  46.8,  46.9,  47. ,  47.1,  47.2,  47.3,  47.4,
        47.5,  47.6,  47.7,  47.8,  47.9,  48. ,  48.1,  48.2,  48.3,
        48.4,  48.5,  48.6,  48.7,  48.8,  48.9,  49. ,  49.1,  49.2,
        49.3,  49.4,  49.5,  49.6,  49.7,  49.8,  49.9,  50. ,  50.1,
        50.2,  50.3,  50.4,  50.5,  50.6,  50.7,  50.8,  50.9,  51. ,
        51.1,  51.2,  51.3,  51.4,  51.5,  51.6,  51.7,  51.8,  51.9,
        52. ,  52.1,  52.2,  52.3,  52.4,  52.5,  52.6,  52.7,  52.8,
        52.9,  53. ,  53.1,  53.2,  53.3,  53.4,  53.5,  53.6,  53.7,
        53.8,  53.9,  54. ,  54.1,  54.2,  54.3,  54.4,  54.5,  54.6,
        54.7,  54.8,  54.9,  55. ,  55.1,  55.2,  55.3,  55.4,  55.5,
        55.6,  55.7,  55.8,  55.9,  56. ,  56.1,  56.2,  56.3,  56.4,
        56.5,  56.6,  56.7,  56.8,  56.9,  57. ,  57.1,  57.2,  57.3,
        57.4,  57.5,  57.6,  57.7,  57.8,  57.9,  58. ,  58.1,  58.2,
        58.3,  58.4,  58.5,  58.6,  58.7,  58.8,  58.9,  59. ,  59.1,
        59.2,  59.3,  59.4,  59.5,  59.6,  59.7,  59.8,  59.9,  60. ,
        60.1,  60.2,  60.3,  60.4,  60.5,  60.6,  60.7,  60.8,  60.9,
        61. ,  61.1,  61.2,  61.3,  61.4,  61.5,  61.6,  61.7,  61.8,
        61.9,  62. ,  62.1,  62.2,  62.3,  62.4,  62.5,  62.6,  62.7,
        62.8,  62.9,  63. ,  63.1,  63.2,  63.3,  63.4,  63.5,  63.6,
        63.7,  63.8,  63.9,  64. ,  64.1,  64.2,  64.3,  64.4,  64.5,
        64.6,  64.7,  64.8,  64.9,  65. ,  65.1,  65.2,  65.3,  65.4,
        65.5,  65.6,  65.7,  65.8,  65.9,  66. ,  66.1,  66.2,  66.3,
        66.4,  66.5,  66.6,  66.7,  66.8,  66.9,  67. ,  67.1,  67.2,
        67.3,  67.4,  67.5,  67.6,  67.7,  67.8,  67.9,  68. ,  68.1,
        68.2,  68.3,  68.4,  68.5,  68.6,  68.7,  68.8,  68.9,  69. ,
        69.1,  69.2,  69.3,  69.4,  69.5,  69.6,  69.7,  69.8,  69.9,
        70. ,  70.1,  70.2,  70.3,  70.4,  70.5,  70.6,  70.7,  70.8,
        70.9,  71. ,  71.1,  71.2,  71.3,  71.4,  71.5,  71.6,  71.7,
        71.8,  71.9,  72. ,  72.1,  72.2,  72.3,  72.4,  72.5,  72.6,
        72.7,  72.8,  72.9,  73. ,  73.1,  73.2,  73.3,  73.4,  73.5,
        73.6,  73.7,  73.8,  73.9,  74. ,  74.1,  74.2,  74.3,  74.4,
        74.5,  74.6,  74.7,  74.8,  74.9,  75. ,  75.1,  75.2,  75.3,
        75.4,  75.5,  75.6,  75.7,  75.8,  75.9,  76. ,  76.1,  76.2,
        76.3,  76.4,  76.5,  76.6,  76.7,  76.8,  76.9,  77. ,  77.1,
        77.2,  77.3,  77.4,  77.5,  77.6,  77.7,  77.8,  77.9,  78. ,
        78.1,  78.2,  78.3,  78.4,  78.5,  78.6,  78.7,  78.8,  78.9,
        79. ,  79.1,  79.2,  79.3,  79.4,  79.5,  79.6,  79.7,  79.8,
        79.9,  80. ,  80.1,  80.2,  80.3,  80.4,  80.5,  80.6,  80.7,
        80.8,  80.9,  81. ,  81.1,  81.2,  81.3,  81.4,  81.5,  81.6,
        81.7,  81.8,  81.9,  82. ,  82.1,  82.2,  82.3,  82.4,  82.5,
        82.6,  82.7,  82.8,  82.9,  83. ,  83.1,  83.2,  83.3,  83.4,
        83.5,  83.6,  83.7,  83.8,  83.9,  84. ,  84.1,  84.2,  84.3,
        84.4,  84.5,  84.6,  84.7,  84.8,  84.9,  85. ,  85.1,  85.2,
        85.3,  85.4,  85.5,  85.6,  85.7,  85.8,  85.9,  86. ,  86.1,
        86.2,  86.3,  86.4,  86.5,  86.6,  86.7,  86.8,  86.9,  87. ,
        87.1,  87.2,  87.3,  87.4,  87.5,  87.6,  87.7,  87.8,  87.9,
        88. ,  88.1,  88.2,  88.3,  88.4,  88.5,  88.6,  88.7,  88.8,
        88.9,  89. ,  89.1,  89.2,  89.3,  89.4,  89.5,  89.6,  89.7,
        89.8,  89.9,  90. ,  90.1,  90.2,  90.3,  90.4,  90.5,  90.6,
        90.7,  90.8,  90.9,  91. ,  91.1,  91.2,  91.3,  91.4,  91.5,
        91.6,  91.7,  91.8,  91.9,  92. ,  92.1,  92.2,  92.3,  92.4,
        92.5,  92.6,  92.7,  92.8,  92.9,  93. ,  93.1,  93.2,  93.3,
        93.4,  93.5,  93.6,  93.7,  93.8,  93.9,  94. ,  94.1,  94.2,
        94.3,  94.4,  94.5,  94.6,  94.7,  94.8,  94.9,  95. ,  95.1,
        95.2,  95.3,  95.4,  95.5,  95.6,  95.7,  95.8,  95.9,  96. ,
        96.1,  96.2,  96.3,  96.4,  96.5,  96.6,  96.7,  96.8,  96.9,
        97. ,  97.1,  97.2,  97.3,  97.4,  97.5,  97.6,  97.7,  97.8,
        97.9,  98. ,  98.1,  98.2,  98.3,  98.4,  98.5,  98.6,  98.7,
        98.8,  98.9,  99. ,  99.1,  99.2,  99.3,  99.4,  99.5,  99.6,
        99.7,  99.8,  99.9, 100. , 100.1, 100.2, 100.3, 100.4, 100.5,
       100.6, 100.7, 100.8, 100.9, 101. , 101.1, 101.2, 101.3, 101.4,
       101.5, 101.6, 101.7, 101.8, 101.9, 102. , 102.1, 102.2, 102.3,
       102.4, 102.5, 102.6, 102.7, 102.8, 102.9, 103. , 103.1, 103.2,
       103.3, 103.4, 103.5, 103.6, 103.7, 103.8, 103.9, 104. , 104.1,
       104.2, 104.3, 104.4, 104.5, 104.6, 104.7, 104.8, 104.9, 105. ,
       105.1, 105.2, 105.3, 105.4, 105.5, 105.6, 105.7, 105.8, 105.9,
       106. , 106.1, 106.2, 106.3, 106.4, 106.5, 106.6, 106.7, 106.8,
       106.9, 107. , 107.1, 107.2, 107.3, 107.4, 107.5, 107.6, 107.7,
       107.8, 107.9, 108. , 108.1, 108.2, 108.3, 108.4, 108.5, 108.6,
       108.7, 108.8, 108.9, 109. , 109.1, 109.2, 109.3, 109.4, 109.5,
       109.6, 109.7, 109.8, 109.9, 110. , 110.1, 110.2, 110.3, 110.4,
       110.5, 110.6, 110.7, 110.8, 110.9, 111. , 111.1, 111.2, 111.3,
       111.4, 111.5, 111.6, 111.7, 111.8, 111.9, 112. , 112.1, 112.2,
       112.3, 112.4, 112.5, 112.6, 112.9, 113. , 113.1, 113.2, 113.3,
       113.4, 113.5, 113.6, 113.7, 113.8, 114. , 114.1, 114.2, 114.3,
       114.8, 114.9, 115. , 115.2, 115.3, 115.6, 116. , 116.1, 116.5,
       116.7, 116.9, 117.2, 117.3, 117.5, 117.6, 117.9, 118. , 118.2,
       118.4, 118.8, 119.8, 120.4, 120.5, 120.8, 120.9, 121.2, 121.3,
       121.6, 121.9, 122. , 122.3, 122.5, 122.6, 122.7, 122.8, 123. ,
       123.1, 123.2, 124.2, 125. , 127.7])

In [129]:
wdm = round(np.mean(wd))

In [130]:
hdm = round(np.mean(hd))

In [131]:
df1["HeightCm"] = df1['HeightCm'].apply(lambda x : x if x in hd else hdm)

In [132]:
df1["WeightKg"] = df1['WeightKg'].apply(lambda x : x if x in wd else wdm)

In [140]:
def bmi(df):
    return round(df['WeightKg'] / (df['HeightCm'] / 100) ** 2, 2)

In [141]:
bmi(df1)

0        35.19
1        12.99
2        13.42
3        23.94
4        28.22
         ...
60895    17.44
60896    17.70
60897    22.36
60898    19.88
60899    12.25
Length: 60030, dtype: float64

In [142]:

df1[['HeightCm', 'WeightKg']].head(50)

    HeightCm  WeightKg
0      157.5      87.3
1      184.7      44.3
2      159.2      34.0
3      165.4      65.5
4      165.5      77.3
5      159.9      95.4
6      186.1      82.3
7      158.7      87.8
9      165.0      71.9
10     165.0      75.6
11     161.5      72.0
12     174.8      95.7
13     187.8      70.0
14     162.4      32.6
15     165.0      50.8
16     182.6      80.0
17     156.8      53.7
18     160.2      72.0
19     181.7      77.4
20     172.2      82.8
21     159.4      76.0
22     174.2      62.4
23     152.6      32.4
24     178.9      57.6
25     148.3      72.0
26     157.8      74.1
27     171.7      47.3
28     155.4      71.9
29     168.1      86.7
30     173.7      72.0
31     160.6      83.2
32     168.0      57.8
33     176.4      79.3
34     172.5      68.0
35     183.2      73.2
36     159.6      54.2
37     158.0      89.4
38     181.2      60.4
39     171.8      74.5
40     168.0     101.1
41     162.2      64.2
42     176.1      67.1
43     164.1      60.9
44     175.8      86.5
45     180.7      84.8
46     169.0      90.0
47     154.4      95.7
48     173.7      52.1
49     179.1      71.4
50     180.0      67.1

In [144]:
df1['BMI'] =bmi(df1)

In [146]:
df1['BMI']

0        35.19
1        12.99
2        13.42
3        23.94
4        28.22
         ...
60895    17.44
60896    17.70
60897    22.36
60898    19.88
60899    12.25
Name: BMI, Length: 60030, dtype: float64