In [2]:
import pandas as pd
schedule = pd.read_csv("train_schedule.csv")
train_info = pd.read_csv("train_info.csv")
schedule.shape
# train_info.shape

(186074, 12)

In [3]:
train_info.shape

(11113, 5)

In [7]:
train_info.info
train_info

,Train_No,Train_Name,Source_Station_Name,Destination_Station_Name,days
0,107,SWV-MAO-VLNK,SAWANTWADI ROAD,MADGOAN JN.,Saturday
1,108,VLNK-MAO-SWV,MADGOAN JN.,SAWANTWADI ROAD,Friday
2,128,MAO-KOP SPEC,MADGOAN JN.,CHHATRAPATI SHAHU MAHARAJ TERMINUS,Friday
3,290,PALACE ON WH,DELHI-SAFDAR JANG,DELHI-SAFDAR JANG,Wednesday
4,401,BSB BHARATDA,AURANGABAD,VARANASI JN.,Saturday
...,...,...,...,...,...
11108,99904,PUNE-TGN EMU,PUNE JN.,TALEGAON,Tuesday
11109,99905,EMU,TALEGAON,SHIVAJINAGAR,Monday
11110,99906,EMU,PUNE JN.,TALEGAON,Wednesday
11111,99907,EMU,TALEGAON,PUNE JN.,Thursday
11112,99908,EMU,PUNE JN.,TALEGAON,Sunday

In [8]:
schedule.info()
schedule

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186074 entries, 0 to 186073
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   SN              186074 non-null  int64
 1   Train_No        186074 non-null  int64
 2   Station_Code    186074 non-null  object
 3   1A              186074 non-null  int64
 4   2A              186074 non-null  int64
 5   3A              186074 non-null  int64
 6   SL              186074 non-null  int64
 7   Station_Name    186064 non-null  object
 8   Route_Number    186074 non-null  int64
 9   Arrival_time    186064 non-null  object
 10  Departure_Time  186074 non-null  object
 11  Distance        186064 non-null  float64
dtypes: float64(1), int64(7), object(4)
memory usage: 17.0+ MB

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0.0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32.0
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49.0
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78.0
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
186069,1,22439,NDLS,100,100,100,100,NEW DELHI,1,00:00:00,06:00:00,0.0
186070,2,22439,UMB,1095,896,697,1095,AMBALA CANT JN,1,08:08:00,08:10:00,199.0
186071,3,22439,LDH,1660,1348,1036,1660,LUDHIANA JN,1,09:19:00,09:21:00,312.0
186072,4,22439,JAT,2985,2408,1831,2985,JAMMU TAWI,1,12:38:00,12:40:00,577.0
186073,5,22439,SVDK,3375,2720,2065,3375,SHMATA VD KATRA,1,14:00:00,00:00:00,655.0

In [9]:
schedule.describe(include="all")

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
count,186074.000000,186074.000000,186074,186074.000000,186074.000000,186074.000000,186074.000000,186064,186074.0,186064,186074,186064.000000
unique,NaN,NaN,8147,NaN,NaN,NaN,NaN,8099,NaN,1440,1440,NaN
top,NaN,NaN,CSMT,NaN,NaN,NaN,NaN,CST-MUMBAI,NaN,00:00:00,00:00:00,NaN
freq,NaN,NaN,1027,NaN,NaN,NaN,NaN,1027,NaN,2003,1970,NaN
mean,13.914695,42157.747455,NaN,1506.769189,1225.415351,944.061513,662.735777,NaN,1.0,NaN,NaN,281.338792
std,12.779368,25090.080221,NaN,2418.719821,1934.975856,1451.231892,967.524012,NaN,0.0,NaN,NaN,483.744162
min,1.000000,107.000000,NaN,100.000000,100.000000,100.000000,100.000000,NaN,1.0,NaN,NaN,0.000000
25%,5.000000,17225.000000,NaN,215.000000,192.000000,169.000000,146.000000,NaN,1.0,NaN,NaN,23.000000
50%,11.000000,40050.000000,NaN,465.000000,392.000000,319.000000,246.000000,NaN,1.0,NaN,NaN,73.000000
75%,18.000000,57550.000000,NaN,1555.000000,1264.000000,973.000000,682.000000,NaN,1.0,NaN,NaN,291.000000
max,118.000000,99908.000000,NaN,21400.000000,17140.000000,12880.000000,8620.000000,NaN,1.0,NaN,NaN,4260.000000

In [10]:
train_info.describe(include="all")

,Train_No,Train_Name,Source_Station_Name,Destination_Station_Name,days
count,11113.000000,11103,11103,11113,11103
unique,NaN,7575,921,924,14
top,NaN,TBM-MSB EMU,CST-MUMBAI,CST-MUMBAI,Friday
freq,NaN,139,513,514,1471
mean,49190.570413,NaN,NaN,NaN,NaN
std,28515.986645,NaN,NaN,NaN,NaN
min,107.000000,NaN,NaN,NaN,NaN
25%,22607.000000,NaN,NaN,NaN,NaN
50%,47174.000000,NaN,NaN,NaN,NaN
75%,68012.000000,NaN,NaN,NaN,NaN
max,99908.000000,NaN,NaN,NaN,NaN

In [11]:
schedule.isnull().sum()

SN                 0
Train_No           0
Station_Code       0
1A                 0
2A                 0
3A                 0
SL                 0
Station_Name      10
Route_Number       0
Arrival_time      10
Departure_Time     0
Distance          10
dtype: int64

In [12]:
train_info.isnull().sum()

Train_No                     0
Train_Name                  10
Source_Station_Name         10
Destination_Station_Name     0
days                        10
dtype: int64

In [13]:
(schedule.isnull().sum() / len(schedule) * 100).sort_values(ascending=False)

Station_Name      0.005374
Arrival_time      0.005374
Distance          0.005374
SN                0.000000
Train_No          0.000000
Station_Code      0.000000
1A                0.000000
2A                0.000000
3A                0.000000
SL                0.000000
Route_Number      0.000000
Departure_Time    0.000000
dtype: float64

In [14]:
(train_info.isnull().sum() / len(train_info) * 100).sort_values(ascending=False)

Train_Name                  0.089985
Source_Station_Name         0.089985
days                        0.089985
Train_No                    0.000000
Destination_Station_Name    0.000000
dtype: float64

In [15]:
schedule.duplicated().sum()

0

In [16]:
train_info.duplicated().sum()

0

In [18]:
schedule = schedule.drop_duplicates()
schedule

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0.0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32.0
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49.0
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78.0
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
186069,1,22439,NDLS,100,100,100,100,NEW DELHI,1,00:00:00,06:00:00,0.0
186070,2,22439,UMB,1095,896,697,1095,AMBALA CANT JN,1,08:08:00,08:10:00,199.0
186071,3,22439,LDH,1660,1348,1036,1660,LUDHIANA JN,1,09:19:00,09:21:00,312.0
186072,4,22439,JAT,2985,2408,1831,2985,JAMMU TAWI,1,12:38:00,12:40:00,577.0
186073,5,22439,SVDK,3375,2720,2065,3375,SHMATA VD KATRA,1,14:00:00,00:00:00,655.0

In [19]:
train_info = train_info.drop_duplicates()
train_info

,Train_No,Train_Name,Source_Station_Name,Destination_Station_Name,days
0,107,SWV-MAO-VLNK,SAWANTWADI ROAD,MADGOAN JN.,Saturday
1,108,VLNK-MAO-SWV,MADGOAN JN.,SAWANTWADI ROAD,Friday
2,128,MAO-KOP SPEC,MADGOAN JN.,CHHATRAPATI SHAHU MAHARAJ TERMINUS,Friday
3,290,PALACE ON WH,DELHI-SAFDAR JANG,DELHI-SAFDAR JANG,Wednesday
4,401,BSB BHARATDA,AURANGABAD,VARANASI JN.,Saturday
...,...,...,...,...,...
11108,99904,PUNE-TGN EMU,PUNE JN.,TALEGAON,Tuesday
11109,99905,EMU,TALEGAON,SHIVAJINAGAR,Monday
11110,99906,EMU,PUNE JN.,TALEGAON,Wednesday
11111,99907,EMU,TALEGAON,PUNE JN.,Thursday
11112,99908,EMU,PUNE JN.,TALEGAON,Sunday

In [20]:
schedule.columns = schedule.columns.str.strip()
schedule

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0.0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32.0
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49.0
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78.0
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
186069,1,22439,NDLS,100,100,100,100,NEW DELHI,1,00:00:00,06:00:00,0.0
186070,2,22439,UMB,1095,896,697,1095,AMBALA CANT JN,1,08:08:00,08:10:00,199.0
186071,3,22439,LDH,1660,1348,1036,1660,LUDHIANA JN,1,09:19:00,09:21:00,312.0
186072,4,22439,JAT,2985,2408,1831,2985,JAMMU TAWI,1,12:38:00,12:40:00,577.0
186073,5,22439,SVDK,3375,2720,2065,3375,SHMATA VD KATRA,1,14:00:00,00:00:00,655.0

In [21]:
train_info.columns = train_info.columns.str.strip()
train_info

,Train_No,Train_Name,Source_Station_Name,Destination_Station_Name,days
0,107,SWV-MAO-VLNK,SAWANTWADI ROAD,MADGOAN JN.,Saturday
1,108,VLNK-MAO-SWV,MADGOAN JN.,SAWANTWADI ROAD,Friday
2,128,MAO-KOP SPEC,MADGOAN JN.,CHHATRAPATI SHAHU MAHARAJ TERMINUS,Friday
3,290,PALACE ON WH,DELHI-SAFDAR JANG,DELHI-SAFDAR JANG,Wednesday
4,401,BSB BHARATDA,AURANGABAD,VARANASI JN.,Saturday
...,...,...,...,...,...
11108,99904,PUNE-TGN EMU,PUNE JN.,TALEGAON,Tuesday
11109,99905,EMU,TALEGAON,SHIVAJINAGAR,Monday
11110,99906,EMU,PUNE JN.,TALEGAON,Wednesday
11111,99907,EMU,TALEGAON,PUNE JN.,Thursday
11112,99908,EMU,PUNE JN.,TALEGAON,Sunday

In [22]:
schedule[schedule.isnull().any(axis=1)]

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
1000,11,4831,CUR,1820,1476,1132,788,NaN,1,20:55:00,21:05:00,344.0
1100,13,4921,UMB,505,424,343,262,AMBALA CANTT,1,06:30:00,06:30:00,NaN
5000,26,11021,TK,5795,4656,3517,2378,NaN,1,19:28:00,19:30:00,1139.0
5100,19,11024,SVJR,1740,1412,1084,756,SHIVAJINAGAR,1,07:09:00,07:10:00,NaN
10000,24,12146,NK,8720,6996,5272,3548,NaN,1,03:20:00,03:25:00,1724.0
10100,15,12151,JSG,7305,5864,4423,2982,JHARSUGUDA J,1,20:55:00,21:00:00,NaN
15000,20,12486,ET,6355,5104,3853,2602,NaN,1,12:35:00,12:45:00,1251.0
15100,11,12491,SCC,3625,2920,2215,1510,SITAPUR CANT,1,19:45:00,19:55:00,NaN
20000,6,12762,KMT,1225,1000,775,550,NaN,1,23:09:00,23:10:00,225.0
20100,8,12767,MJRI,1520,1236,952,668,MAJRI JN.,1,22:53:00,22:55:00,NaN
25000,2,13019,SRP,195,176,157,138,NaN,1,22:07:00,22:08:00,19.0
25100,36,13020,HJP,4625,3720,2815,1910,HAJIPUR JN.,1,18:50:00,18:55:00,NaN
30000,12,14036,JHL,1580,1284,988,692,NaN,1,05:55:00,05:58:00,296.0
30100,26,14055,KOJ,3820,3076,2332,1588,KOKRAJHAR,1,16:53:00,16:55:00,NaN
35000,26,15050,NH,4340,3492,2644,1796,NaN,1,03:20:00,03:22:00,848.0
35100,7,15056,BHI,630,524,418,312,BAHERI,1,20:08:00,20:10:00,NaN
40000,4,16031,GDR,785,648,511,374,NaN,1,08:15:00,08:17:00,137.0
40100,23,16032,NRW,2640,2132,1624,1116,NARWANA JN.,1,09:28:00,09:30:00,NaN
45000,15,16794,VM,12165,9752,7339,4926,NaN,1,20:00:00,20:10:00,2413.0
45100,11,16857,PGT,2655,2144,1633,1122,PALAKKAD JN,1,03:25:00,03:30:00,NaN
50000,5,18206,MUR,1130,924,718,512,MANKAPUR JN.,1,NaN,13:10:00,206.0
55000,18,19119,VRL,2250,1820,1390,960,VERAVAL,1,NaN,19:40:00,430.0
60000,20,22443,VAPI,7345,5896,4447,2998,VAPI,1,NaN,20:08:00,1449.0
65000,27,22953,ADI,2550,2060,1570,1080,AHMEDABAD,1,NaN,14:40:00,490.0
70000,5,31631,AGP,180,164,148,132,AGARPARA,1,NaN,23:11:00,16.0
75000,13,33812,BT,370,316,262,208,BARASAT JN.,1,NaN,04:15:00,54.0
80000,9,34826,SBGR,195,176,157,138,SUBHASGRAM,1,NaN,09:28:00,19.0
85000,2,37322,LOK,110,108,106,104,LOKNATH,1,NaN,07:58:00,2.0
90000,12,38410,ULB,290,252,214,176,ULUBARIA,1,NaN,05:51:00,38.0
95000,6,40371,NBK,135,128,121,114,NUNGAMBAKKAM,1,NaN,16:06:00,7.0

In [23]:
schedule = schedule.dropna(
    subset=["Station_Name", "Arrival_time", "Distance"]
)
schedule

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0.0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32.0
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49.0
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78.0
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
186069,1,22439,NDLS,100,100,100,100,NEW DELHI,1,00:00:00,06:00:00,0.0
186070,2,22439,UMB,1095,896,697,1095,AMBALA CANT JN,1,08:08:00,08:10:00,199.0
186071,3,22439,LDH,1660,1348,1036,1660,LUDHIANA JN,1,09:19:00,09:21:00,312.0
186072,4,22439,JAT,2985,2408,1831,2985,JAMMU TAWI,1,12:38:00,12:40:00,577.0
186073,5,22439,SVDK,3375,2720,2065,3375,SHMATA VD KATRA,1,14:00:00,00:00:00,655.0

In [24]:
train_info[train_info.isnull().any(axis=1)]
train_info

,Train_No,Train_Name,Source_Station_Name,Destination_Station_Name,days
0,107,SWV-MAO-VLNK,SAWANTWADI ROAD,MADGOAN JN.,Saturday
1,108,VLNK-MAO-SWV,MADGOAN JN.,SAWANTWADI ROAD,Friday
2,128,MAO-KOP SPEC,MADGOAN JN.,CHHATRAPATI SHAHU MAHARAJ TERMINUS,Friday
3,290,PALACE ON WH,DELHI-SAFDAR JANG,DELHI-SAFDAR JANG,Wednesday
4,401,BSB BHARATDA,AURANGABAD,VARANASI JN.,Saturday
...,...,...,...,...,...
11108,99904,PUNE-TGN EMU,PUNE JN.,TALEGAON,Tuesday
11109,99905,EMU,TALEGAON,SHIVAJINAGAR,Monday
11110,99906,EMU,PUNE JN.,TALEGAON,Wednesday
11111,99907,EMU,TALEGAON,PUNE JN.,Thursday
11112,99908,EMU,PUNE JN.,TALEGAON,Sunday

In [25]:
schedule = schedule.dropna(
    subset=["Station_Name", "Arrival_time", "Distance"]
)
schedule

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0.0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32.0
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49.0
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78.0
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
186069,1,22439,NDLS,100,100,100,100,NEW DELHI,1,00:00:00,06:00:00,0.0
186070,2,22439,UMB,1095,896,697,1095,AMBALA CANT JN,1,08:08:00,08:10:00,199.0
186071,3,22439,LDH,1660,1348,1036,1660,LUDHIANA JN,1,09:19:00,09:21:00,312.0
186072,4,22439,JAT,2985,2408,1831,2985,JAMMU TAWI,1,12:38:00,12:40:00,577.0
186073,5,22439,SVDK,3375,2720,2065,3375,SHMATA VD KATRA,1,14:00:00,00:00:00,655.0

In [26]:
schedule["Arrival_time"] = pd.to_datetime(
    schedule["Arrival_time"],
    format="%H:%M:%S"
)

schedule["Departure_Time"] = pd.to_datetime(
    schedule["Departure_Time"],
    format="%H:%M:%S"
)
schedule

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,1900-01-01 00:00:00,1900-01-01 10:25:00,0.0
1,2,107,THVM,260,228,196,164,THIVIM,1,1900-01-01 11:06:00,1900-01-01 11:08:00,32.0
2,3,107,KRMI,345,296,247,198,KARMALI,1,1900-01-01 11:28:00,1900-01-01 11:30:00,49.0
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,1900-01-01 12:10:00,1900-01-01 00:00:00,78.0
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,1900-01-01 00:00:00,1900-01-01 20:30:00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
186069,1,22439,NDLS,100,100,100,100,NEW DELHI,1,1900-01-01 00:00:00,1900-01-01 06:00:00,0.0
186070,2,22439,UMB,1095,896,697,1095,AMBALA CANT JN,1,1900-01-01 08:08:00,1900-01-01 08:10:00,199.0
186071,3,22439,LDH,1660,1348,1036,1660,LUDHIANA JN,1,1900-01-01 09:19:00,1900-01-01 09:21:00,312.0
186072,4,22439,JAT,2985,2408,1831,2985,JAMMU TAWI,1,1900-01-01 12:38:00,1900-01-01 12:40:00,577.0
186073,5,22439,SVDK,3375,2720,2065,3375,SHMATA VD KATRA,1,1900-01-01 14:00:00,1900-01-01 00:00:00,655.0

In [27]:
schedule["Train_No"].nunique()
schedule

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,1900-01-01 00:00:00,1900-01-01 10:25:00,0.0
1,2,107,THVM,260,228,196,164,THIVIM,1,1900-01-01 11:06:00,1900-01-01 11:08:00,32.0
2,3,107,KRMI,345,296,247,198,KARMALI,1,1900-01-01 11:28:00,1900-01-01 11:30:00,49.0
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,1900-01-01 12:10:00,1900-01-01 00:00:00,78.0
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,1900-01-01 00:00:00,1900-01-01 20:30:00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
186069,1,22439,NDLS,100,100,100,100,NEW DELHI,1,1900-01-01 00:00:00,1900-01-01 06:00:00,0.0
186070,2,22439,UMB,1095,896,697,1095,AMBALA CANT JN,1,1900-01-01 08:08:00,1900-01-01 08:10:00,199.0
186071,3,22439,LDH,1660,1348,1036,1660,LUDHIANA JN,1,1900-01-01 09:19:00,1900-01-01 09:21:00,312.0
186072,4,22439,JAT,2985,2408,1831,2985,JAMMU TAWI,1,1900-01-01 12:38:00,1900-01-01 12:40:00,577.0
186073,5,22439,SVDK,3375,2720,2065,3375,SHMATA VD KATRA,1,1900-01-01 14:00:00,1900-01-01 00:00:00,655.0

In [28]:
train_info["Train_No"].nunique()
train_info

,Train_No,Train_Name,Source_Station_Name,Destination_Station_Name,days
0,107,SWV-MAO-VLNK,SAWANTWADI ROAD,MADGOAN JN.,Saturday
1,108,VLNK-MAO-SWV,MADGOAN JN.,SAWANTWADI ROAD,Friday
2,128,MAO-KOP SPEC,MADGOAN JN.,CHHATRAPATI SHAHU MAHARAJ TERMINUS,Friday
3,290,PALACE ON WH,DELHI-SAFDAR JANG,DELHI-SAFDAR JANG,Wednesday
4,401,BSB BHARATDA,AURANGABAD,VARANASI JN.,Saturday
...,...,...,...,...,...
11108,99904,PUNE-TGN EMU,PUNE JN.,TALEGAON,Tuesday
11109,99905,EMU,TALEGAON,SHIVAJINAGAR,Monday
11110,99906,EMU,PUNE JN.,TALEGAON,Wednesday
11111,99907,EMU,TALEGAON,PUNE JN.,Thursday
11112,99908,EMU,PUNE JN.,TALEGAON,Sunday

In [29]:
train_info["days"].value_counts()
train_info

,Train_No,Train_Name,Source_Station_Name,Destination_Station_Name,days
0,107,SWV-MAO-VLNK,SAWANTWADI ROAD,MADGOAN JN.,Saturday
1,108,VLNK-MAO-SWV,MADGOAN JN.,SAWANTWADI ROAD,Friday
2,128,MAO-KOP SPEC,MADGOAN JN.,CHHATRAPATI SHAHU MAHARAJ TERMINUS,Friday
3,290,PALACE ON WH,DELHI-SAFDAR JANG,DELHI-SAFDAR JANG,Wednesday
4,401,BSB BHARATDA,AURANGABAD,VARANASI JN.,Saturday
...,...,...,...,...,...
11108,99904,PUNE-TGN EMU,PUNE JN.,TALEGAON,Tuesday
11109,99905,EMU,TALEGAON,SHIVAJINAGAR,Monday
11110,99906,EMU,PUNE JN.,TALEGAON,Wednesday
11111,99907,EMU,TALEGAON,PUNE JN.,Thursday
11112,99908,EMU,PUNE JN.,TALEGAON,Sunday

In [30]:
schedule[["1A", "2A", "3A", "SL"]].describe()
schedule

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,1900-01-01 00:00:00,1900-01-01 10:25:00,0.0
1,2,107,THVM,260,228,196,164,THIVIM,1,1900-01-01 11:06:00,1900-01-01 11:08:00,32.0
2,3,107,KRMI,345,296,247,198,KARMALI,1,1900-01-01 11:28:00,1900-01-01 11:30:00,49.0
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,1900-01-01 12:10:00,1900-01-01 00:00:00,78.0
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,1900-01-01 00:00:00,1900-01-01 20:30:00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
186069,1,22439,NDLS,100,100,100,100,NEW DELHI,1,1900-01-01 00:00:00,1900-01-01 06:00:00,0.0
186070,2,22439,UMB,1095,896,697,1095,AMBALA CANT JN,1,1900-01-01 08:08:00,1900-01-01 08:10:00,199.0
186071,3,22439,LDH,1660,1348,1036,1660,LUDHIANA JN,1,1900-01-01 09:19:00,1900-01-01 09:21:00,312.0
186072,4,22439,JAT,2985,2408,1831,2985,JAMMU TAWI,1,1900-01-01 12:38:00,1900-01-01 12:40:00,577.0
186073,5,22439,SVDK,3375,2720,2065,3375,SHMATA VD KATRA,1,1900-01-01 14:00:00,1900-01-01 00:00:00,655.0

In [33]:
merged_data = schedule.merge(
    train_info,
    on="Train_No",
    how="left"
)
schedule

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,1900-01-01 00:00:00,1900-01-01 10:25:00,0.0
1,2,107,THVM,260,228,196,164,THIVIM,1,1900-01-01 11:06:00,1900-01-01 11:08:00,32.0
2,3,107,KRMI,345,296,247,198,KARMALI,1,1900-01-01 11:28:00,1900-01-01 11:30:00,49.0
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,1900-01-01 12:10:00,1900-01-01 00:00:00,78.0
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,1900-01-01 00:00:00,1900-01-01 20:30:00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
186069,1,22439,NDLS,100,100,100,100,NEW DELHI,1,1900-01-01 00:00:00,1900-01-01 06:00:00,0.0
186070,2,22439,UMB,1095,896,697,1095,AMBALA CANT JN,1,1900-01-01 08:08:00,1900-01-01 08:10:00,199.0
186071,3,22439,LDH,1660,1348,1036,1660,LUDHIANA JN,1,1900-01-01 09:19:00,1900-01-01 09:21:00,312.0
186072,4,22439,JAT,2985,2408,1831,2985,JAMMU TAWI,1,1900-01-01 12:38:00,1900-01-01 12:40:00,577.0
186073,5,22439,SVDK,3375,2720,2065,3375,SHMATA VD KATRA,1,1900-01-01 14:00:00,1900-01-01 00:00:00,655.0